### PR TITLE
Azure log analytics scaler now supports the unsafeSsl flag

### LINKED ISSUE #4046: Keda doesn't work with TLS inspection
I have noticed that there is no parameter to configure cabundle for TLS inspection support.
(Specific with azure log analytics scaler)

Thanks!

### PR DESCRIPTION
**Pull request by raz-bn**
Allow users to configure whether or not they want to use SSL when using the azure monitor log analytic scaler.
Inspired by the Loki scaler.

Relates to #4046 

default value still remains false.

### CODE REVIEW

**Comment by Zurielevi** [comment]
Hi
Can you approve this pull request?

**Review by JorTurFer — COMMENTED** [review]
sorry, I missed this PR :( 
Could you add a test to validate the new parameter parsing behaviour and also the docs explaining it?

File: pkg/scalers/azure_log_analytics_scaler.go [hunk 1]
```diff
@@ -229,6 +232,17 @@ func parseAzureLogAnalyticsMetadata(config *ScalerConfig) (*azureLogAnalyticsMet
...
+	// Getting unsafeSsl, observe that we dont check AuthParams for unsafeSsl
+	unsafeSslVal, err := getParameterFromConfig(config, "unsafeSsl", false)
+	if err != nil {
+		unsafeSslVal = "false"
+	}
+	unsafeSsl, err := strconv.ParseBool(unsafeSslVal)
+	if err != nil {
+		return nil, fmt.Errorf("error parsing metadata. Details: can't parse unsafeSsl. Inner Error: %w", err)
+	}
+	meta.unsafeSsl = unsafeSsl
```
Comment (JorTurFer) [inline pkg/scalers/azure_log_analytics_scaler.go:244]:
```suggestion
	meta.unsafeSsl = false
	unsafeSslVal, err := getParameterFromConfig(config, "unsafeSsl", false)
	if err == nil {	
		unsafeSsl, err := strconv.ParseBool(unsafeSslVal)
		if err != nil {
			return nil, fmt.Errorf("error parsing metadata. Details: can't parse unsafeSsl. Inner Error: %w", err)
		}
		meta.unsafeSsl = unsafeSsl
	}
```

**Comment by raz-bn** [comment]
@JorTurFer Hey! I resolved the changes you suggested and also added tests for the variable. 
Where should I doc it? Can you point me to where I should do it?

**Comment by raz-bn** [comment]
@JorTurFer 
https://github.com/kedacore/keda-docs/pull/1041
I created a PR for the docs :)

**Comment by Zurielevi** [comment]
Hi
Can you approve this PR?

**Review by JorTurFer — APPROVED** [review]
LGTM! Thanks for the improvement ❤️ 
I'll wait to merge this till the docs PR is ready
