### PR TITLE
fix: ensure consistent JSON log format for automaxprocs

### LINKED ISSUE #5970: Automaxprocs library prints log in a different format then the rest of the KEDA operator
### Report

With the addition of the automaxprocs package to set GOMAXPROCS (https://github.com/kedacore/keda/issues/4999), the KEDA operator now prints one console type log on startup, then switches to the format configured by `logging.operator.format`:

```
2024/07/18 20:58:55 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
2024-07-18T20:58:57.052292080Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Starting manager"}
2024-07-18T20:58:57.052312817Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"KEDA Version: 2.13.1"}
{"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Git Commit: 41dd7a8558fdb274f2c0861f6c6d1eba01f2dcd5"}
2024-07-18T20:58:57.052319615Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Go Version: go1.21.6"}
2024-07-18T20:58:57.052321484Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Go OS/Arch: linux/amd64"}
2024-07-18T20:58:57.052323828Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Running on Kubernetes 1.29+","version":"v1.29.4-eks-036c24b"}
2024-07-18T20:58:57.153119735Z I0718 20:58:57.153022       1 leaderelection.go:250] attempting to acquire leader lease h6m-core-keda/operator.keda.sh...
2024-07-18T20:58:57.153330709Z {"level":"info","ts":"2024-07-18T20:58:57Z","msg":"starting server","kind":"health probe","addr":"[::]:8081"}
```
We are running KEDA in an environment where this is breaking our log ingestion, as we expect only one log format. The way to disable this logging, or implement it with the same logger as the rest app, is documented here: https://github.com/uber-go/automaxprocs/issues/18.

### Expected Behavior

When setting the `logging.operator.format` to `json`, I expect all logs produced by the KEDA operator to be in JSON format.

### Actual Behavior

When running KEDA operator, there is one log printed by the `automaxprocs` package that doesn't respect the format as configured by the user.

### Steps to Reproduce the Problem

1. Run KEDA Operator 
2. Observe logs

### Logs from KEDA operator

```
2024/07/18 20:58:55 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
2024-07-18T20:58:57.052292080Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Starting manager"}
2024-07-18T20:58:57.052312817Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"KEDA Version: 2.13.1"}
{"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Git Commit: 41dd7a8558fdb274f2c0861f6c6d1eba01f2dcd5"}
2024-07-18T20:58:57.052319615Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Go Version: go1.21.6"}
2024-07-18T20:58:57.052321484Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Go OS/Arch: linux/amd64"}
2024-07-18T20:58:57.052323828Z {"level":"info","ts":"2024-07-18T20:58:57Z","logger":"setup","msg":"Running on Kubernetes 1.29+","version":"v1.29.4-eks-036c24b"}
2024-07-18T20:58:57.153119735Z I0718 20:58:57.153022       1 leaderelection.go:250] attempting to acquire leader lease h6m-core-keda/operator.keda.sh...
2024-07-18T20:58:57.153330709Z {"level":"info","ts":"2024-07-18T20:58:57Z","msg":"starting server","kind":"health probe","addr":"[::]:8081"}
```

### KEDA Version

2.13.1

### Kubernetes Version

1.29

### Platform

Amazon Web Services

### Scaler Details

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by omerap12**
Configures automaxprocs to use the application logger instead of default console logging to maintain consistent JSON format across all log output.
output:
```
keda-admission-webhooks:
 ~/ k logs deployments.apps/keda-admission-webhooks -n keda
2024-11-15T18:39:05Z	INFO	setup	maxprocs: Updating GOMAXPROCS=1: determined from CPU quota	{"system": "automaxprocs"}
2024-11-15T18:39:05Z	INFO	setup	Starting admission webhooks
2024-11-15T18:39:05Z	INFO	setup	KEDA Version: main
2024-11-15T18:39:05Z	INFO	setup	Git Commit: c2a6df04230e1f62d335127e0a02694015c79fa6
2024-11-15T18:39:05Z	INFO	setup	Go Version: go1.23.3
2024-11-15T18:39:05Z	INFO	setup	Go OS/Arch: linux/arm64
2024-11-15T18:39:05Z	INFO	setup	Running on Kubernetes 1.30	{"version": "v1.30.0"}
2024-11-15T18:39:05Z	INFO	controller-runtime.builder	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "keda.sh/v1alpha1, Kind=ScaledObject"}
```

keda-operator:
```
 ~/ k logs deployment/keda-operator -n keda
2024-11-15T18:39:00Z	INFO	setup	maxprocs: Updating GOMAXPROCS=1: determined from CPU quota	{"system": "automaxprocs"}
2024-11-15T18:39:00Z	INFO	setup	Starting manager
2024-11-15T18:39:00Z	INFO	setup	KEDA Version: main
2024-11-15T18:39:00Z	INFO	setup	Git Commit: c2a6df04230e1f62d335127e0a02694015c79fa6
2024-11-15T18:39:00Z	INFO	setup	Go Version: go1.23.3
2024-11-15T18:39:00Z	INFO	setup	Go OS/Arch: linux/arm64
2024-11-15T18:39:00Z	INFO	setup	Running on Kubernetes 1.30	{"version": "v1.30.0"}
2024-11-15T18:39:01Z	INFO	starting server	{"name": "health probe", "addr": "[::]:8081"}
I1115 18:39:01.071646       1 leaderelection.go:254] attempting to acquire leader lease keda/operator.keda.sh...
I1115 18:39:39.767722       1 leaderelection.go:268] successfully acquired lease keda/operator.keda.sh
```

keda-operator-metrics-apiserver:
```
 ~/ k logs deployments.apps/keda-operator-metrics-apiserver -n keda                       
I1115 18:38:55.350590       1 welcome.go:34] "msg"="Starting metrics server" "logger"="keda_metrics_adapter"
I1115 18:38:55.350752       1 welcome.go:35] "msg"="KEDA Version: main" "logger"="keda_metrics_adapter"
I1115 18:38:55.350756       1 welcome.go:36] "msg"="Git Commit: c2a6df04230e1f62d335127e0a02694015c79fa6" "logger"="keda_metrics_adapter"
I1115 18:38:55.350759       1 welcome.go:37] "msg"="Go Version: go1.23.3" "logger"="keda_metrics_adapter"
I1115 18:38:55.350761       1 welcome.go:38] "msg"="Go OS/Arch: linux/arm64" "logger"="keda_metrics_adapter"
I1115 18:38:55.350775       1 welcome.go:39] "msg"="Running on Kubernetes 1.30" "logger"="keda_metrics_adapter" "version"={"major":"1","minor":"30","gitVersion":"v1.30.0","gitCommit":"7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a","gitTreeState":"clean","buildDate":"2024-05-13T22:02:25Z","goVersion":"go1.22.2","compiler":"gc","platform":"linux/arm64"}
I1115 18:38:55.350913       1 main.go:263] "msg"="maxprocs: Updating GOMAXPROCS=1: determined from CPU quota" "logger"="keda_metrics_adapter"
I1115 18:38:55.351645       1 main.go:112] "msg"="Connecting Metrics Service gRPC client to the server" "address"="keda-operator.keda.svc.cluster.local:9666" "logger"="keda_metrics_adapter"
```

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #5970

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
Thanks, this is great!

Could you please define this in a single place and just reference in each component? The best place is probably a new file in https://github.com/kedacore/keda/tree/main/pkg/util

**Comment by omerap12** [comment]
> Thanks, this is great!
> 
> Could you please define this in a single place and just reference in each component? The best place is probably a new file in https://github.com/kedacore/keda/tree/main/pkg/util

fixed :)

**Review by zroubalik — APPROVED** [review]

**Comment by zroubalik** [comment]
@omerap12 could you please also update Changelog? https://github.com/kedacore/keda/blob/main/CHANGELOG.md#improvements-1

**Comment by omerap12** [comment]
> @omerap12 could you please also update Changelog? https://github.com/kedacore/keda/blob/main/CHANGELOG.md#improvements-1

Done

File: cmd/adapter/main.go [hunk 1]
```diff
@@ -257,6 +256,12 @@ func main() {
 		return
 	}
 
+	err = kedautil.ConfigureMaxProcs(logger)
+	if err != nil {
+		logger.Error(err, "failed to set max procs")
+		return
```
Comment (wozniakjan) [inline cmd/adapter/main.go:262]: nit: should this also have exit code 1 to be consistent with other components?
```suggestion
		os.Exit(1)
```

Comment (omerap12) [reply cmd/adapter/main.go:262]: I noticed that all the errors are simply returned, like: [here](https://github.com/kedacore/keda/blob/main/cmd/adapter/main.go#L257). so I chose not to modify the existing error-handling behavior.

Comment (wozniakjan) [reply cmd/adapter/main.go:262]: sure, just wondering if it makes sense to unify the behavior
https://github.com/kedacore/keda/blob/0a1d8be9296cfc2dd9be20c2cdaebf9fa1c7a010/cmd/operator/main.go#L118-L122
https://github.com/kedacore/keda/blob/0a1d8be9296cfc2dd9be20c2cdaebf9fa1c7a010/cmd/webhooks/main.go#L82-L86

but it's just a cosmetic change, I'm ok with either path

Comment (omerap12) [reply cmd/adapter/main.go:262]: I can create a separate PR to adjust all error codes in the main function to `Exit(1)` if you'd like. but, I think this is behind the scope of the current PR

**Review by wozniakjan — APPROVED** [review]

**Comment by omerap12** [comment]
> /run-e2e internal **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/11915308768)

Passed. can we merge it? :)

**Review by JorTurFer — COMMENTED** [review]
LGTM! Could you move the changelog entry to the unreleased section? after the release it was moved to v2.16 and should be unreleased yet

**Comment by omerap12** [comment]
> LGTM! Could you move the changelog entry to the unreleased section? after the release it was moved to v2.16 and should be unreleased yet

hopes I did it right this time lol

**Comment by wozniakjan** [comment]
/skip-e2e
(last commit is just CHANGELOG.md change, previous commit e2e tests passed)
