### PR TITLE
Fix issue with Azure Pipelines PAT Auth

### LINKED ISSUE #3159: Azure Pipelines Scaled Object cannot reconcile due to wrong PAT config
I've run into this:

```
1.6549081369500506e+09	INFO	controller.scaledobject	Creating a new HPA	{"reconciler group": "keda.sh", "reconcilerkind": "ScaledObject", "name": "azure-pipelines-scaledobject", "namespace": "azdevops", "HPA.Namespace": "azdevops", "HPA.Name": "keda-hpa-azure-pipelines-scaledobject"}
1.6549081373579395e+09	ERROR	scalehandler	error resolving auth params	{"scalerIndex": 0, "object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "azdevops", "name": "azure-pipelines-scaledobject"}, "error": "error parsing azure Pipelines metadata: the Azure DevOps REST API returned error. url: https://dev.azure.com/xxxxxx/_apis/distributedtask/pools?poolName=AWS-K8s status: 401 response: "}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:181
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:64
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).createAndDeployNewHPA
	/workspace/controllers/keda/hpa.go:47
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:369
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:231
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:182
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227
```

To test that my PAT was working I used this [script](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Linux#use-a-pat) from the Azure Docs. (Works good)

### PR DESCRIPTION
**Pull request by raravena80**
Fixes #3159 

Signed-off-by: Ricardo Aravena <raravena80@gmail.com>

Fix issue with Azure Pipelines PAT Auth

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added 
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)* - N/A
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) - N/A
- [x] Changelog has been updated and is aligned with our [changelog requirements] (https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #3159 

Relates to #

### CODE REVIEW

File: pkg/scalers/azure_pipelines_scaler.go [hunk 1]
```diff
@@ -178,7 +178,7 @@ func getAzurePipelineRequest(ctx context.Context, url string, metadata *azurePip
 		return []byte{}, err
 	}
 
-	req.SetBasicAuth("PAT", metadata.personalAccessToken)
+	req.SetBasicAuth("", strings.TrimSuffix(metadata.personalAccessToken, "\n"))
```
Comment (JorTurFer) [inline pkg/scalers/azure_pipelines_scaler.go:181]: I'm not sure if removing the header PAT it'll work (let's see the e2e test how it finishes). I agree with removing any new line at the end, but please do it in the metadata parsing to do it only once.
Could you add a unit test for this please?

Comment (raravena80) [reply pkg/scalers/azure_pipelines_scaler.go:181]: @JorTurFer is there already a unit test? https://github.com/kedacore/keda/blob/main/tests/scalers/azure-pipelines.test.ts. Is there something more specific that I can add to that test?

Comment (JorTurFer) [reply pkg/scalers/azure_pipelines_scaler.go:183]: hey,
yes, there is a file for [unit tests](https://github.com/kedacore/keda/blob/main/pkg/scalers/azure_pipelines_scaler_test.go). You could add this check to the `TestParseAzurePipelinesMetadata` as a validation in [the api stub](https://github.com/kedacore/keda/blob/main/pkg/scalers/azure_pipelines_scaler_test.go#L42).

Also remove this line because it's duplicated (at least in GH UI :/ ) 
image

File: pkg/scalers/azure_pipelines_scaler_test.go [hunk 2]
```diff
@@ -27,6 +27,8 @@ var testAzurePipelinesMetadata = []parseAzurePipelinesMetadataTestData{
 	{"all properly formed", map[string]string{"organizationURLFromEnv": "AZP_URL", "personalAccessTokenFromEnv": "AZP_TOKEN", "poolID": "1", "targetPipelinesQueueLength": "1"}, false, testAzurePipelinesResolvedEnv, map[string]string{}},
 	// using triggerAuthentication
 	{"using triggerAuthentication", map[string]string{"poolID": "1", "targetPipelinesQueueLength": "1"}, false, testAzurePipelinesResolvedEnv, map[string]string{"organizationURL": "https://dev.azure.com/sample", "personalAccessToken": "sample"}},
+	// using triggerAuthentication with personalAccessToken terminating in newline
+	{"using triggerAuthentication with personalAccessToken terminating in newline", map[string]string{"poolID": "1", "targetPipelinesQueueLength": "1"}, false, testAzurePipelinesResolvedEnv, map[string]string{"organizationURL": "https://dev.azure.com/sample", "personalAccessToken": "sample\n"}},
```
Comment (JorTurFer) [inline pkg/scalers/azure_pipelines_scaler_test.go:31]: only this doesn't test anything, you need to add the checking code inside the mock server handler

File: pkg/scalers/azure_pipelines_scaler_test.go [hunk 3]
```diff
@@ -41,8 +41,13 @@ func TestParseAzurePipelinesMetadata(t *testing.T) {
 	for _, testData := range testAzurePipelinesMetadata {
 		t.Run(testData.testName, func(t *testing.T) {
 			var apiStub = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
-				w.WriteHeader(http.StatusOK)
-				_, _ = w.Write([]byte(`{"count":1,"value":[{"id":1}]}`))
+				personalAccessToken := testData.authParams["personalAccessToken"]	
+				if personalAccessToken != "" && personalAccessToken[len(personalAccessToken)-1:] == "\n" {
```
Comment (JorTurFer) [inline pkg/scalers/azure_pipelines_scaler_test.go:45]: you are not checking the parsed PAT here, you are using the provided by the input data.
When I said about adding this here, I meant to check in the `http.Request` headers if the PAT always comes without the `/n` even the input contains it

Comment (raravena80) [reply pkg/scalers/azure_pipelines_scaler_test.go]: Made the changes, not sure how to trigger the negative check though.

**Comment by JorTurFer** [comment]
Looking good. Please solve the conflicts 🙏 
Then I'll trigger e2e tests and if they pass, the PR is ready.
Thanks for the contribution ❤️

**Review by JorTurFer — APPROVED** [review]
Thanks a lot! 🙇

**Comment by raravena80** [comment]
> Thanks a lot! 🙇

Finally! 😄
