### PR TITLE
accept 'disable' as a valid tls value for kafka scaler

### LINKED ISSUE #2608: No way to specify TLS disabled for Kafka scaler
### Report

When using the Apache Kafka scaler, you can set the auth parameter `tls` to `enabled` for the underlying kafka client to use tls when connecting to the brokers. There is no way however to set `tls` to anything else to configure tls to be disabled. See [here](https://github.com/kedacore/keda/blob/main/pkg/scalers/kafka_scaler.go#L170-L189). Now I know that the default behavior is that tls is off but the current behavior is counter-intuitive.

### Expected Behavior

`tls: disabled` is not invalid and means the same as not specifying the parameter

### Actual Behavior

The scaler throws an error

### Steps to Reproduce the Problem

1. Create a trigger authentication resource that exposes the tls parameter as "disabled"
2. Create a kafka scaler that references the trigger auth
3. The scaler can't be created because the tls value is invalid

### Logs from KEDA operator

_No response_

### KEDA Version

2.6.0

### Kubernetes Version

1.20

### Platform

Amazon Web Services

### Scaler Details

Kafka

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gunniwho**
Signed-off-by: Gunnar Palsson <gunniwho@gmail.com>

_Provide a description of what has been changed_

Accepts `disable` as a valid value for the `tls` auth parameter of the kafka scaler.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A [PR](https://github.com/kedacore/keda-docs/pull/648) is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #2608

### CODE REVIEW

File: pkg/scalers/kafka_scaler.go [hunk 1]
```diff
@@ -183,7 +183,7 @@ func parseKafkaMetadata(config *ScalerConfig) (kafkaMetadata, error) {
 			meta.cert = config.AuthParams["cert"]
 			meta.key = config.AuthParams["key"]
 			meta.enableTLS = true
-		} else {
+		} else if val != "disable" {
```
Comment (tomkerkhove) [inline pkg/scalers/kafka_scaler.go:186]: What happens if the value is not `enable` nor `disable`?

Comment (tomkerkhove) [reply pkg/scalers/kafka_scaler.go:186]: Oh I see now.

**Review by tomkerkhove — APPROVED** [review]

**Review by zroubalik — COMMENTED** [review]
@gunniwho could you please add some tests for this parameter?

**Comment by gunniwho** [comment]
@zroubalik I could try but I don't have any experience writing go code. Should the test be added to the kafka scaler e2e tests?

**Comment by zroubalik** [comment]
@gunniwho thanks, unit tests are enough for this feature imho, they are located here: https://github.com/kedacore/keda/blob/main/pkg/scalers/kafka_scaler_test.go

it is just about adding validation for this field. Thanks a lot!

**Comment by JorTurFer** [comment]
I'm missing something, is not adding `dissable` like having the default value? 
I mean, in this case `tls` refeers the authentication method and not the usage of `SSL/TLS` protocol itself. Probably I'm wrong because I have never used kafka before, but reading the docs that's what I understand

**Comment by nilayasiktoprak** [comment]
> I'm missing something, is not adding `disable` like having the default value? I mean, in this case `tls` refers to the authentication method and not the usage of `SSL/TLS` protocol itself. Probably I'm wrong because I have never used Kafka before, but reading the docs that's what I understand

I agree with @JorTurFer. In the docs( https://keda.sh/docs/2.6/scalers/apache-kafka/#authentication-parameters ), it is indicated that if you don't pass the tls value, it means it's disabled which is the default. So that's the way to disable tls if you don't want to use it.  
However, I think it's a better practice to pass the tls anyway whether it's enabled or disabled in the yaml so that it will be more clear.

**Comment by JorTurFer** [comment]
The point is that in this case it could be confusing because TLS sounds like transport encryption and not like client authentication method. Maybe we should rename them into more explicit keys. 
Also, the documentation is wrong because `true` and `false` are invalid values:

image

IMHO we should rename the authentication method and honor TLS key if we want to allow secure/insecure traffic (if Kafka supports it, IDK) or keep it there for backward compatibility during some versions if not. But related with this, I don't see any necessity of adding extra code to explicitly set `disable`. Removing the else block sounds more correct to me (and it'll allow `disable` too).

WDYT @kedacore/keda-core-contributors ?

BTW: Thanks for exposing the problem and for the contribution ❤️ ❤️ ❤️

**Comment by gunniwho** [comment]
@JorTurFer I agree that it would be better to just remove the else block, effectively saying that passing anything other than 'enable' for this value just means that it's not enabled. It was annoying that it was throwing errors for seemingly no reason.

Regarding the docs, I also did  [PR](https://github.com/kedacore/keda-docs/pull/648) to fix them (for 2.7.0 - was asked to also fix for previous versions).

Regarding the TLS naming, I don't have an opinion at all...

**Comment by JorTurFer** [comment]
The point is that `tls` usually means `Transport Layer Security` but in Kafka scaler (AFAIK) means SSL authentication. You can use user/password (`sasl`) or certificate (`tls`). It's not related with the common meaning of `tls` and it could be confusing. 
My proposal is renaming `tls` into `certificate` and decide if we want to support (if Kafka supports it) `Transport Layer Security` do it like we are doing in other scalers with something like `unsafeSsl` or similar.

**Comment by gunniwho** [comment]
The `tls` option is not synonymous with `certificate` authentication for this scaler. It can be used to authenticate using certs (I think) but it is also the way to specify that you want to use the `SASL` authentication over a secured connection. If you specify `sasl` and not `tls` the credentials (or hashes in the case of scram) are sent over an insecure connection.

File: pkg/scalers/kafka_scaler.go (hunk 1 above)
Comment (JorTurFer) [reply pkg/scalers/kafka_scaler.go:186]: Could it be better if we remove the whole else block?

Comment (JorTurFer) [reply pkg/scalers/kafka_scaler.go:186]: onle `enabled` will enable it and other values will do nothing

Comment (tomkerkhove) [reply pkg/scalers/kafka_scaler.go:186]: Using `disabled` to be explicit in the scaled object should not be blocked though. Which is the problem today.

Better be explicit than make assumptions.

**Comment by gunniwho** [comment]
> @gunniwho thanks, unit tests are enough for this feature imho, they are located here: https://github.com/kedacore/keda/blob/main/pkg/scalers/kafka_scaler_test.go
> 
> it is just about adding validation for this field. Thanks a lot!

done

**Review by JorTurFer — APPROVED** [review]
LGTM!

**Comment by JorTurFer** [comment]
hey @gunniwho ,
Your last 2 commits are not signed. Could you sign them? 
https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what

**Review by JorTurFer — APPROVED** [review]
Thanks for your contribution ❤️
