### PR TITLE
Metrics Server: print a message on successful connection to gRPC server

### LINKED ISSUE #4190: Connection error from keda-operator-metrics-apiserver logs
### Report

After updating KEDA to version 2.9.2 (via chart version 2.9.3) from version 2.8.1 the metrics apiserver logs shows connection issue from the keda operator service at port 9666 

### Expected Behavior

The keda metrics apiserver to be able to use gRPC connection to successfully get metrics from operator

### Actual Behavior

When I deployed the latest KEDA version 2.9.2 started seeing the below error in the metrics apiserver logs,

I0201 19:41:19.967541       1 main.go:162] keda_metrics_adapter "msg"="Connecting Metrics Service gRPC client to the server" "address"="keda-operator.mynamespace.svc.cluster.local:9666"

Err: connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 502 Bad Gateway\\r\\n

### Steps to Reproduce the Problem

Update KEDA version from 2.8.1 to 2.9.2

### Logs from KEDA operator

```
I0201 19:41:19.967541       1 main.go:162] keda_metrics_adapter "msg"="Connecting Metrics Service gRPC client to the server" "address"="keda-operator.<MYNAMESPACE>.svc.cluster.local:9666"

Err: connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 502 Bad Gateway\\r\\n
```

### KEDA Version

2.9.2

### Kubernetes Version

1.23

### Platform

Amazon Web Services

### Scaler Details

_No response_

### Anything else?

The keda service (13-keda-service.yaml) was introduced with the latest version referring to this issue https://github.com/kedacore/keda/issues/3920 as this service wasn't there in the older version

I can try KEDA_USE_METRICS_SERVICE_GRPC=false but as it will be deprecated, wanted to see how to resolve the issue

KEDA runs behind enterprise proxy and the values are set via HTTP_PROXY HTTPS_PROXY and NO_PROXY

### PR DESCRIPTION
**Pull request by zroubalik**
Metrics Server: print a message on successful connection to gRPC server.
Also rearanged the startup logic a little bit, to make the output log more clear.

### Checklist

- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4190

### CODE REVIEW

File: pkg/provider/provider.go [hunk 1]
```diff
@@ -72,6 +74,18 @@ func NewProvider(ctx context.Context, adapterLogger logr.Logger, scaleHandler sc
 	}
 	logger = adapterLogger.WithName("provider")
 	logger.Info("starting")
+
+	go func() {
+		if !grpcClient.WaitForConnectionReady(ctx, logger) {
+			grpcClientConnected = false
+			logger.Error(fmt.Errorf("timeout while waiting to establish gRPC connection to KEDA Metrics Service server"), "timeout", "server", grpcClient.GetServerURL())
+		}
```
Comment (JorTurFer) [inline pkg/provider/provider.go:82]: I think that this if case should have a return, otherwise if the connection fails, we will log the error and also the successful connection

**Review by JorTurFer — APPROVED** [review]
LGTM! One comment inline

File: pkg/provider/provider.go (hunk 1 above)
Comment (zroubalik) [reply pkg/provider/provider.go:82]: Good catch, thanks! It should be in the `else`. I refactored this part several times and probably end up with something broken 😄

Comment (JorTurFer) [reply pkg/provider/provider.go]: What about just adding the return? We can save one indentation level. Something like:
```golang
	go func() {
		if !grpcClient.WaitForConnectionReady(ctx, logger) {
			grpcClientConnected = false
			logger.Error(fmt.Errorf("timeout while waiting to establish gRPC connection to KEDA Metrics Service server"), "timeout", "server", grpcClient.GetServerURL())
			return
		}
		if !grpcClientConnected {
			grpcClientConnected = true
			logger.Info("Connection to KEDA Metrics Service gRPC server has been successfully established", "server", grpcClient.GetServerURL())
		}
	}()
```
