### PR TITLE
fix(kafka-scaler): return error if partition processing fails

### LINKED ISSUE #4098: Kafka scaler | Scale to 0 during Kafka broker replacement even if the fallback is configured
### Report

Hello,

we periodically encounter an issue with some of the ScaledObjects with the Kafka trigger during Kafka broker replacement. Even if we configure the fallback the deployment is scaled to 0. In the case, where I will provide shrinked operator logs for it took approx. 2h for the fallback mechanism to kick in.

### Expected Behavior

During faulty Kafka responses, deployment goes to the amount of PODs configured in `fallback.replicas`

### Actual Behavior

Deployment goes to 0 during Kafka broker replacement and recovers after a long period to the number set in `fallback.replicas`

### Steps to Reproduce the Problem

Here the ScaledObject we use

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-kafka-scaling
  namespace: zzz
spec:
  cooldownPeriod: 300
  fallback:
    failureThreshold: 3
    replicas: 1
  idleReplicaCount: 0
  maxReplicaCount: 2
  minReplicaCount: 1
  pollingInterval: 30
  scaleTargetRef:
    name: foo-deployment
  triggers:
    - authenticationRef:
        name: keda-trigger-kafka-auth
      metadata:
        activationLagThreshold: '1'
        allowIdleConsumers: 'false'
        bootstrapServers: bootstrapserver:28751
        consumerGroup: consumergroup
        lagThreshold: '50000'
        offsetResetPolicy: earliest
        scaleToZeroOnInvalidOffset: 'false'
        topic: FOO
      type: kafka
```

### Logs from KEDA operator

```
2023-01-10T18:42:05Z	ERROR	kafka_scaler		{"type": "ScaledObject", "namespace": "zzz", "name": "keda-kafka-scaling", "error": "error listing consumer group offsets: kafka server: Request was for a consumer group that is not coordinated by this broker"}
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getConsumerAndProducerOffsets.func1
	/workspace/pkg/scalers/kafka_scaler.go:461
2023-01-10T18:42:05Z	ERROR	kafka_scaler		{"type": "ScaledObject", "namespace": "zzz", "name": "keda-kafka-scaling", "error": "error finding offset block for topic FOO and partition 0"}
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getTotalLag
	/workspace/pkg/scalers/kafka_scaler.go:511
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).IsActive
	/workspace/pkg/scalers/kafka_scaler.go:268
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive
	/workspace/pkg/scaling/cache/scalers_cache.go:89
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
2023-01-10T18:42:05Z	ERROR	kafka_scaler		{"type": "ScaledObject", "namespace": "zzz", "name": "keda-kafka-scaling", "error": "error finding offset block for topic FOO and partition 1"}
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getTotalLag
	/workspace/pkg/scalers/kafka_scaler.go:511
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).IsActive
	/workspace/pkg/scalers/kafka_scaler.go:268
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive
	/workspace/pkg/scaling/cache/scalers_cache.go:89
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
.
.
.
2023-01-10T20:06:37Z	ERROR	kafka_scaler		{"type": "ScaledObject", "namespace": "zzz", "name": "keda-kafka-scaling", "error": "error listing consumer group offsets: kafka server: Request was for a consumer group that is not coordinated by this broker"}
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getConsumerAndProducerOffsets.func1
	/workspace/pkg/scalers/kafka_scaler.go:461
2023-01-10T20:06:37Z	ERROR	kafka_scaler		{"type": "ScaledObject", "namespace": "zzz", "name": "keda-kafka-scaling", "error": "error finding offset block for topic FOO and partition 2"}
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getTotalLag
	/workspace/pkg/scalers/kafka_scaler.go:511
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).IsActive
	/workspace/pkg/scalers/kafka_scaler.go:268
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive
	/workspace/pkg/scaling/cache/scalers_cache.go:89
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
2023-01-10T20:06:37Z	ERROR	kafka_scaler		{"type": "ScaledObject", "namespace": "zzz", "name": "keda-kafka-scaling", "error": "error finding offset block for topic FOO and partition 0"}
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getTotalLag
	/workspace/pkg/scalers/kafka_scaler.go:511
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).IsActive
	/workspace/pkg/scalers/kafka_scaler.go:268
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).IsScaledObjectActive
	/workspace/pkg/scaling/cache/scalers_cache.go:89
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
.
.
.
2023-01-10T20:10:07Z	ERROR	kafka_scaler		{"type": "ScaledObject", "namespace": "zzz", "name": "keda-kafka-scaling", "error": "error listing consumer group offsets: kafka server: Request was for a consumer group that is not coordinated by this broker"}
github.com/kedacore/keda/v2/pkg/scalers.(*kafkaScaler).getConsumerAndProducerOffsets.func1
	/workspace/pkg/scalers/kafka_scaler.go:461
2023-01-10T20:10:08Z	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "keda-clickhouse-ingester-scaling", "scaledObject.Namespace": "inventory-platform-services", "scaleTarget.Name": "clickhouse-ingester", "error": "kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
2023-01-10T20:10:09Z	ERROR	scalehandler	Error getting scale decision	{"scaledobject.Name": "keda-kafka-scaling", "scaledObject.Namespace": "zzz", "scaleTarget.Name": "foo-deployment", "error": "kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:278
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:149
2023-01-10T20:10:09Z	INFO	scaleexecutor	Successfully set ScaleTarget replicas count to ScaledObject fallback.replicas	{"scaledobject.Name": "keda-kafka-scaling", "scaledObject.Namespace": "zzz", "scaleTarget.Name": "foo-deployment", "Original Replicas Count": 0, "New Replicas Count": 1}

```

### KEDA Version

2.8.1

### Kubernetes Version

1.23

### Platform

Amazon Web Services

### Scaler Details

Kafka

### Anything else?

From this Graph (kube_deployment_status_replicas) you can see the scaling of the Deployment going to 0. The time fits the log I provided.
Screenshot 2023-01-12 at 13 25 29

### PR DESCRIPTION
**Pull request by sdomme**
Signed-off-by: Sergej Domme <sergej.domme@idealo.de>

This fix allows to return an error during the partition iteration in case the process of getting the lag from the partition fails finding the block.

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4098

### CODE REVIEW

File: pkg/scalers/kafka_scaler.go [hunk 1]
```diff
@@ -592,7 +592,10 @@ func (s *kafkaScaler) getTotalLag() (int64, int64, error) {
 
 	for topic, partitionsOffsets := range producerOffsets {
 		for partition := range partitionsOffsets {
-			lag, lagWithPersistent, _ := s.getLagForPartition(topic, partition, consumerOffsets, producerOffsets)
+			lag, lagWithPersistent, err := s.getLagForPartition(topic, partition, consumerOffsets, producerOffsets)
+			if err != nil {
+				return 0, 0, err
```
Comment (zroubalik) [inline pkg/scalers/kafka_scaler.go:597]: might be benefitical to pring error log message here as well, with the info about the problematci partition.

File: CHANGELOG.md [hunk 2]
```diff
@@ -71,7 +71,8 @@ Here is an overview of all new **experimental** features:
 - **General**: Prevent a panic that might occur while refreshing a scaler cache ([#4092](https://github.com/kedacore/keda/issues/4092))
 - **Azure Service Bus Scaler:** Use correct auth flows with pod identity ([#4026](https://github.com/kedacore/keda/issues/4026)|[#4123](https://github.com/kedacore/keda/issues/4123))
 - **CPU Memory Scaler** Store forgotten logger ([#4022](https://github.com/kedacore/keda/issues/4022))
-  **Kafka Scaler**: Support 0 in activationLagThreshold configuration ([#4137](https://github.com/kedacore/keda/issues/4137))
+- **Kafka Scaler**: Support 0 in activationLagThreshold configuration ([#4137](https://github.com/kedacore/keda/issues/4137))
```
Comment (zroubalik) [inline CHANGELOG.md:74]: please sort alphabetically

File: pkg/scalers/kafka_scaler.go (hunk 1 above)
Comment (sdomme) [reply pkg/scalers/kafka_scaler.go:597]: could you please elaborate? Since the error log message is already printed here
https://github.com/kedacore/keda/blob/415b48335be73ed5887ca3d756a83d33a98df619/pkg/scalers/kafka_scaler.go#L447-L449
We just not ignoring it anymore. Or am I misunderstanding something?

Comment (zroubalik) [reply pkg/scalers/kafka_scaler.go:597]: You are right, I missed this one. Please disregard :)

File: CHANGELOG.md (hunk 2 above)
Comment (sdomme) [reply CHANGELOG.md:74]: For the lines you marked I just add a hyphen for one of the [previous contributions](https://github.com/kedacore/keda/commit/15805c99fdb5da242e8725777a03a479459af79f).  Or you mean to swap
```
- **Kafka Scaler**: Support 0 ...
- **Kafka Scaler**: Return ...
```

this lines?

Comment (sdomme) [reply CHANGELOG.md]: I swapped the lines. Should be fine now.

**Comment by zroubalik** [comment]
@sdomme could you please fix the DCO? then we can go ahead and merge this

The fix instructions can be found in the Details: https://github.com/kedacore/keda/pull/4149/checks?check_run_id=10870127333
or:
```
1. In your local branch, run: git rebase HEAD~4 --signoff
2. Force push your changes to overwrite the branch: git push --force-with-lease origin fix/return-error-on-partition-fail
```

**Comment by sdomme** [comment]
@zroubalik Is it somehow stuck in a workflow? Can I do something here?

**Review by zroubalik — APPROVED** [review]
LGTM
