### PR TITLE
logging for errors when a blob container is not found in Azure event hubs scaler

### LINKED ISSUE #2363: Azure Event Hub scaler doesn't log anything if the blob container name is wrong
While querying the scaling metric, if the scaler for Azure Event Hub cannot find the blob storage container the error message never gets logged.
Instead, the total amount of events in the hub is used as the value for the metric, whether they have already been handled or not.

This is due to the codeblock starting from the line in this link:
https://github.com/kedacore/keda/blob/7b9817325fd88f291af6a224899bd385cb86bb3c/pkg/scalers/azure_eventhub_scaler.go#L168

Due to this it is currently incredibly difficult to locate an error caused by a wrong blob storage container name.

### PR DESCRIPTION
**Pull request by SushmithaVReddy**
Added logging for errors when a blob container is not found in Azure event hubs scaler

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] Tests have been added
- [ ] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [ ] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)

Fixes #2363

### CODE REVIEW

File: pkg/scalers/azure_eventhub_scaler.go [hunk 1]
```diff
@@ -171,6 +171,8 @@ func (scaler *azureEventHubScaler) GetUnprocessedEventCountInPartition(ctx conte
 		err = errors.Unwrap(err)
 		if stErr, ok := err.(azblob.StorageError); ok {
 			if stErr.ServiceCode() == azblob.ServiceCodeBlobNotFound || stErr.ServiceCode() == azblob.ServiceCodeContainerNotFound {
+				fmt.Errorf("Blob container : %s not found to use checkpoint strategy, error : %s", scaler.metadata.eventHubInfo.BlobContainer, err)
+				fmt.Println("Getting unprocessed event count without checkpoint")
```
Comment (JorTurFer) [inline pkg/scalers/azure_eventhub_scaler.go:175]: This case is not a critical error, is more like an execution condition. 
Could you print those messages in V(1)?
```suggestion
				eventhubLog.V(1).Error(err, fmt.Sprintf("Blob container : %s not found to use checkpoint strategy, error : %s", scaler.metadata.eventHubInfo.BlobContainer, err))
				eventhubLog.V(1).Info("Getting unprocessed event count without checkpoint")
```

**Review by JorTurFer — COMMENTED** [review]
Thanks for the contribution
Only small nit

File: pkg/scalers/azure_eventhub_scaler.go (hunk 1 above)
Comment (zroubalik) [reply pkg/scalers/azure_eventhub_scaler.go:175]: do we need to print both error and info log message? Isn't just one (info on debug) enough? In case this error is not critical.

Comment (JorTurFer) [reply pkg/scalers/azure_eventhub_scaler.go:175]: I assume is not critical because we don't return the error, so I guess that it's another code path.
Merging both messages in one is good idea IMO

Comment (SushmithaVReddy) [reply pkg/scalers/azure_eventhub_scaler.go:175]: I was also wondering about the fatality of this error. I see we move on and get the count of events using partition count, but the user seems uninformed of this or at least hasn't subscribed to this mechanism for scaling decision. Any thoughts on this?

Comment (JorTurFer) [reply pkg/scalers/azure_eventhub_scaler.go:175]: I'm not an expert in Azure EventHub and its internals.
Do you know about it @tomkerkhove @ahmelsayed ?

**Comment by SushmithaVReddy** [comment]
> Thanks for the contribution Only small nit

Modified the logging to use eventhubLog and combined the log messages too.

**Review by zroubalik — COMMENTED** [review]
Could you please also update the Changelo?

File: pkg/scalers/azure_eventhub_scaler.go (hunk 1 above)
Comment (tomkerkhove) [reply pkg/scalers/azure_eventhub_scaler.go]: I'm not sure I get the question, sorry :/ Can you elaborate on it please?

**Comment by SushmithaVReddy** [comment]
> Could you please also update the Changelog?

Done @zroubalik

File: pkg/scalers/azure_eventhub_scaler.go (hunk 1 above)
Comment (JorTurFer) [reply pkg/scalers/azure_eventhub_scaler.go]: wdyt about the fatality of this error?

Comment (SushmithaVReddy) [reply pkg/scalers/azure_eventhub_scaler.go]: @tomkerkhove As the code suggests, if a blob container is not found we get the event count as the number of messages in the partition. But, if the user has mentioned a checkpoint strategy they meant to use the blob container and process event count, so is silently logging an error and moving on to get event count from partition right?

**Comment by zroubalik** [comment]
@SushmithaVReddy could you please rebase once again and move the Changelog entry to `Improvements` section?
Also could you please fix DCO? https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what

Then we can proceed with the merge, thanks!

**Comment by SushmithaVReddy** [comment]
> @SushmithaVReddy could you please rebase once again and move the Changelog entry to `Improvements` section? Also could you please fix DCO? https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#i-didnt-sign-my-commit-now-what
> 
> Then we can proceed with the merge, thanks!

Done @zroubalik

**Review by zroubalik — APPROVED** [review]

**Comment by zroubalik** [comment]
Thanks @SushmithaVReddy !
