### PR TITLE
fix: Admission Webhook blocks ScaledObject without metricType with fallback

### LINKED ISSUE #6696: Admission Webhook blocks ScaledObject with fallback (using AverageValue) 2.17
### Report

We rolled out 2.17.0 in our dev stack yesterday. We are now unable to deploy `ScaledObject` resources with a `fallback`. We receive the following error:

>  admission webhook "vscaledobject.kb.io" denied the request: at least one trigger (that is not cpu or memory) has to have the `AverageValue` type for the fallback to be enabled

These particular scalers are using the `type=redis`. The HPA's generated by the scalers (at least, pre 2.17) contain an `AverageValue` metric so the error does not make sense to me

### Expected Behavior

Rollout should succeed when `fallback` is specified.

### Actual Behavior

Unable to roll out `ScaledObject` with the following error:
>  admission webhook "vscaledobject.kb.io" denied the request: at least one trigger (that is not cpu or memory) has to have the `AverageValue` type for the fallback to be enabled

### Steps to Reproduce the Problem

1. Keda 2.17.0
2. Apply the following manifests

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-redis-secret
  namespace: default
type: Opaque
data:
  redis_username: YWRtaW4=
  redis_password: YWRtaW4=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: my-redis-auth
  namespace: default
spec:
  secretTargetRef:
  - parameter: username
    name: my-redis-secret
    key: redis_username
  - parameter: password
    name: my-redis-secret
    key: redis_password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-queue-trigger
  namespace: default
spec:
  cooldownPeriod: 300
  fallback:
    behavior: static
    failureThreshold: 3
    replicas: 1
  maxReplicaCount: 1
  minReplicaCount: 0
  pollingInterval: 30
  scaleTargetRef:
    name: myproject
  triggers:
    - authenticationRef:
        name: my-redis-auth
      metadata:
        databaseIndex: '0'
        enableTLS: 'true'
        listLength: '5'
        listName: q:my:in
        port: '6380'
      type: redis
    - authenticationRef:
        name: my-redis-auth
      metadata:
        databaseIndex: '0'
        enableTLS: 'true'
        listLength: '5'
        listName: q:my:wait
        port: '6380'
      type: redis
```

3. Fail

### Logs from KEDA operator

Webhook logs (there were not logs in the operator)

```
2025-04-08T12:44:45Z    INFO    triggerauthentication-validation-webhook        validating triggerauthentication creation for {
  "kind": "TriggerAuthentication",
  "apiVersion": "keda.sh/v1alpha1",
  "metadata": {
    "name": "my-redis-auth",
    "namespace": "default",
    "uid": "1aa13de3-45a1-47c5-8df3-f707bc66961d",
    "generation": 1,
    "creationTimestamp": "2025-04-08T12:44:45Z",
    "managedFields": [
      {
        "manager": "kubectl",
        "operation": "Apply",
        "apiVersion": "keda.sh/v1alpha1",
        "time": "2025-04-08T12:44:45Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:spec": {
            "f:secretTargetRef": {}
          }
        }
      }
    ]
  },
  "spec": {
    "secretTargetRef": [
      {
        "parameter": "username",
        "name": "my-redis-secret",
        "key": "redis_username"
      },
      {
        "parameter": "password",
        "name": "my-redis-secret",
        "key": "redis_password"
      }
    ]
  },
  "status": {}
}
2025-04-08T12:44:45Z    ERROR   scaledobject-validation-webhook validation error        {"name": "my-queue-trigger", "error": "at least one trigger (that is not cpu or memory) has to have the `AverageValue` type for the fallback to be enabled"}
github.com/kedacore/keda/v2/apis/keda/v1alpha1.verifyFallback
        /workspace/apis/keda/v1alpha1/scaledobject_webhook.go:196
github.com/kedacore/keda/v2/apis/keda/v1alpha1.validateWorkload
        /workspace/apis/keda/v1alpha1/scaledobject_webhook.go:161
github.com/kedacore/keda/v2/apis/keda/v1alpha1.(*ScaledObject).ValidateCreate
        /workspace/apis/keda/v1alpha1/scaledobject_webhook.go:118
github.com/kedacore/keda/v2/apis/keda/v1alpha1.ScaledObjectCustomValidator.ValidateCreate
        /workspace/apis/keda/v1alpha1/scaledobject_webhook.go:90
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*validatorForType).Handle
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go:91
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:181
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:119
sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics.InstrumentedHook.InstrumentHandlerInFlight.func1
        /workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:60
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2220
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
        /workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:147
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2220
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
        /workspace/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:109
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2220
net/http.(*ServeMux).ServeHTTP
        /usr/local/go/src/net/http/server.go:2747
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:2092
```

### KEDA Version

2.17.0

### Kubernetes Version

1.30

### Platform

Microsoft Azure

### Scaler Details

Redis

### Anything else?

This is an example of the HPA generated on the previous version. Note that the metric has a target of `AverageValue`

```yaml
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: keda-hpa-my-queue-trigger
  labels:
    scaledobject.keda.sh/name: my-queue-trigger
  ownerReferences:
    - apiVersion: keda.sh/v1alpha1
      kind: ScaledObject
      name: my-queue-trigger
      uid: 41f2d8b7-d614-49a9-a303-e58e4f58996c
      controller: true
      blockOwnerDeletion: true
spec:
  scaleTargetRef:
    kind: Deployment
    name: myproject
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: External
      external:
        metric:
          name: s0-redis-q-my-in
          selector:
            matchLabels:
              scaledobject.keda.sh/name: my-queue-trigger
        target:
          type: AverageValue
          averageValue: '5'
    - type: External
      external:
        metric:
          name: s1-redis-q-my-wait
          selector:
            matchLabels:
              scaledobject.keda.sh/name: my-queue-trigger
        target:
          type: AverageValue
          averageValue: '10'
```

### PR DESCRIPTION
**Pull request by rickbrouwer**
In scaler.go there is a function [GetMetricTargetType](https://github.com/kedacore/keda/blob/main/pkg/scalers/scaler.go#L114-L124) which helps get the metric target type of the scaler. If no metric type is provided then the AverageValue is used.

In v2.17 is a check in the webhook admission that if at least one trigger is of the type `AverageValue`, then having fallback is valid. A `metricType` is optional and often not supplied. As a result, many scaledObjects now give errors when supplying a fallback without `metricType`.

Adding an extra check if the `trigger.MetricType` is empty will fix this issue. This check is also in the [scaler.go](https://github.com/kedacore/keda/blob/main/pkg/scalers/scaler.go#L114-L124).

Any feedback regarding the chosen solution is okay.

### Checklist

- [X] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #6696

### CODE REVIEW

**Review by wozniakjan — APPROVED** [review]
thank you!

could you please also add an e2e test for this case so future KEDA releases are a bit safer? Don't feel pressured, if it's not in your capacity at the moment, I'm happy to approve this as is and add the e2e test coverage later this week.

**Comment by rickbrouwer** [comment]
> thank you!
> 
> could you please also add an e2e test for this case so future KEDA releases are a bit safer? Don't feel pressured, if it's not in your capacity at the moment, I'm happy to approve this as is and add the e2e test coverage later this week.

I'll add a unit test first. That also does a good check. I saw that `scaledobject_types` doesn't have this anyway, so here it is :)

I will create a test case in the e2e of fallback later.

**Comment by rickbrouwer** [comment]
Added more unit tests for the remaining functions of scaledobject_types

File: tests/internals/fallback/fallback_test.go [hunk 1]
```diff
@@ -196,6 +196,41 @@ spec:
...
+    app: {{.DeploymentName}}
+spec:
+  scaleTargetRef:
+    name: {{.DeploymentName}}
+  minReplicaCount: {{.MinReplicas}}
+  maxReplicaCount: {{.MaxReplicas}}
+  fallback:
+    failureThreshold: 1
+    replicas: {{.DefaultFallback}}
+    behavior: currentReplicasIfHigher
```
Comment (wozniakjan) [inline tests/internals/fallback/fallback_test.go:215]: just making sure, `behavior` is an optional field, right?

Comment (wozniakjan) [reply tests/internals/fallback/fallback_test.go:215]: yep, it is :)
https://github.com/kedacore/keda/blob/a368eee4333c6328a351201b5b67fa0e0a0fb955/apis/keda/v1alpha1/scaledobject_types.go#L116-L119

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!
