### PR TITLE
fix: stop scale loop for pause Scaledbject (issue #4253)

### LINKED ISSUE #4253: The paused-replicas annotation not fully respected
### Report

Althogh the **scaledobject** annotation **autoscaling.keda.sh/paused-replicas** does pause the autoscaling as expected, keda will still log error messages originating from triggers for such paused scaledobjects. This is a problem if you are managing multiple environments that are being fully scaled down (to 0), including the data sources for the scaled object triggers - in our case mysql database is also scaled down so the database connection failure is all the time logged.

### Expected Behavior

No error messages will be created whatsoever for scaledobjects that are paused.

### Actual Behavior

many errors are logged in loop - see logs from keda operator

### Steps to Reproduce the Problem

1. to pause, type
```bash
kubectl annotate scaledobject session-scaler autoscaling.keda.sh/paused-replicas="0"
```
2. to checkout the operator logs:

k logs -l app=keda-operator -f

4.

### Logs from KEDA operator

```
2023-02-20T14:36:52Z	ERROR	mysql_scaler	Found error when pinging database: dial tcp 100.64.186.148:3306: connect: connection refused	{"type": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler", "error": "dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/pkg/scalers.NewMySQLScaler
	/workspace/pkg/scalers/mysql_scaler.go:53
github.com/kedacore/keda/v2/pkg/scaling.buildScaler
	/workspace/pkg/scaling/scale_handler.go:431
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers.func1
	/workspace/pkg/scaling/scale_handler.go:325
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scale_handler.go:328
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:202
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	scalehandler	error resolving auth params	{"scalerIndex": 0, "object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler"}, "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:202
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	Error getting scalers	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	Failed to create new HPA resource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "HPA.Namespace": "invu-sre", "HPA.Name": "keda-hpa-keda-session-scaler", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	Failed to check HPA for possible update	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	ERROR	Failed to ensure HPA is correctly created for ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:52Z	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"invu-sre","name":"keda-session-scaler","uid":"495af290-9075-4185-81bd-8f2dcebaa40b","apiVersion":"keda.sh/v1alpha1","resourceVersion":"258835449"}, "reason": "KEDAScalerFailed", "message": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
2023-02-20T14:36:52Z	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"invu-sre","name":"keda-session-scaler","uid":"495af290-9075-4185-81bd-8f2dcebaa40b","apiVersion":"keda.sh/v1alpha1","resourceVersion":"258835449"}, "reason": "ScaledObjectCheckFailed", "message": "Failed to ensure HPA is correctly created for ScaledObject"}
2023-02-20T14:36:52Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "d6eaaaf7-5633-4e16-9093-7108dbfb736e", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3"}
2023-02-20T14:36:55Z	DEBUG	Parsed Group, Version, Kind, Resource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "GVK": "apps/v1.Deployment", "Resource": "deployments"}
2023-02-20T14:36:55Z	DEBUG	scalehandler	cannot resolve env to a value. fieldRef and resourceFieldRef env are skipped	{"type": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler", "env-var-name": "INSTANCE"}
2023-02-20T14:36:55Z	DEBUG	scalehandler	cannot resolve env to a value. fieldRef and resourceFieldRef env are skipped	{"type": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler", "env-var-name": "MY_POD_NAMESPACE"}
2023-02-20T14:36:55Z	ERROR	mysql_scaler	Found error when pinging database: dial tcp 100.64.186.148:3306: connect: connection refused	{"type": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler", "error": "dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/pkg/scalers.NewMySQLScaler
	/workspace/pkg/scalers/mysql_scaler.go:53
github.com/kedacore/keda/v2/pkg/scaling.buildScaler
	/workspace/pkg/scaling/scale_handler.go:431
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers.func1
	/workspace/pkg/scaling/scale_handler.go:325
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).buildScalers
	/workspace/pkg/scaling/scale_handler.go:328
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:202
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	scalehandler	error resolving auth params	{"scalerIndex": 0, "object": {"apiVersion": "keda.sh/v1alpha1", "kind": "ScaledObject", "namespace": "invu-sre", "name": "keda-session-scaler"}, "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScalersCache
	/workspace/pkg/scaling/scale_handler.go:194
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).getScaledObjectMetricSpecs
	/workspace/controllers/keda/hpa.go:202
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	Error getting scalers	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).newHPAForScaledObject
	/workspace/controllers/keda/hpa.go:74
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).updateHPAIfNeeded
	/workspace/controllers/keda/hpa.go:152
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	Failed to create new HPA resource	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "HPA.Namespace": "invu-sre", "HPA.Name": "keda-hpa-keda-session-scaler", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).ensureHPAForScaledObjectExists
	/workspace/controllers/keda/scaledobject_controller.go:410
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	Failed to check HPA for possible update	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).reconcileScaledObject
	/workspace/controllers/keda/scaledobject_controller.go:241
github.com/kedacore/keda/v2/controllers/keda.(*ScaledObjectReconciler).Reconcile
	/workspace/controllers/keda/scaledobject_controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	ERROR	Failed to ensure HPA is correctly created for ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
2023-02-20T14:36:55Z	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"invu-sre","name":"keda-session-scaler","uid":"495af290-9075-4185-81bd-8f2dcebaa40b","apiVersion":"keda.sh/v1alpha1","resourceVersion":"258835449"}, "reason": "KEDAScalerFailed", "message": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
2023-02-20T14:36:55Z	DEBUG	events	Warning	{"object": {"kind":"ScaledObject","namespace":"invu-sre","name":"keda-session-scaler","uid":"495af290-9075-4185-81bd-8f2dcebaa40b","apiVersion":"keda.sh/v1alpha1","resourceVersion":"258835449"}, "reason": "ScaledObjectCheckFailed", "message": "Failed to ensure HPA is correctly created for ScaledObject"}
2023-02-20T14:36:55Z	ERROR	Reconciler error	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"keda-session-scaler","namespace":"invu-sre"}, "namespace": "invu-sre", "name": "keda-session-scaler", "reconcileID": "a09319ae-39da-4f3b-bf57-b1ddf85f18c3", "error": "error establishing MySQL connection: dial tcp 100.64.186.148:3306: connect: connection refused"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234

```

### KEDA Version

2.8.1

### Kubernetes Version

1.25

### Platform

Amazon Web Services

### Scaler Details

mysql

### Anything else?

willing to help fix this

### PR DESCRIPTION
**Pull request by tobotg**
In the controller in the reconcile loop, when a scaledObject is paused (annotated with ), this fix stops the scaling logic (to prevent attempt to connect the to scalers), and deletes the generated HPA (so it is not querying KEDA Metric Server for metrics)

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #4253

### CODE REVIEW

**Comment by tobotg** [comment]
@zroubalik @tomkerkhove Resubmitting a new PR.

**Review by zroubalik — COMMENTED** [review]
Great, could you please update this PR to contain newest commits? there are some improvements in e2e tests logging, thanks!

File: controllers/keda/scaledobject_controller.go [hunk 1]
```diff
@@ -437,6 +451,31 @@ func (r *ScaledObjectReconciler) ensureHPAForScaledObjectExists(ctx context.Cont
 	return false, nil
 }
 
+// ensureHPAForScaledObjectIsDeleted ensures that in cluster any HPA for specified ScaledObject is deleted, returns true if no HPA exists
+func (r *ScaledObjectReconciler) ensureHPAForScaledObjectIsDeleted(ctx context.Context, logger logr.Logger, scaledObject *kedav1alpha1.ScaledObject) (bool, error) {
+	var hpaName string
+	if scaledObject.Status.HpaName != "" {
+		hpaName = scaledObject.Status.HpaName
+	} else {
+		hpaName = getHPAName(scaledObject)
```
Comment (zroubalik) [inline controllers/keda/scaledobject_controller.go:460]: Could you please include this logic inside `getHPAName()`? Please update this also in the rest of the codebase.

File: controllers/keda/scaledobject_controller.go [hunk 2]
```diff
@@ -437,6 +451,31 @@ func (r *ScaledObjectReconciler) ensureHPAForScaledObjectExists(ctx context.Cont
...
+	}
+	foundHpa := &autoscalingv2.HorizontalPodAutoscaler{}
+	// Check if HPA for this ScaledObject already exists
+	err := r.Client.Get(ctx, types.NamespacedName{Name: hpaName, Namespace: scaledObject.Namespace}, foundHpa)
+	if err != nil && errors.IsNotFound(err) {
+		return true, nil
+	} else if err != nil {
+		logger.Error(err, "Failed to get HPA from cluster")
```
Comment (zroubalik) [inline controllers/keda/scaledobject_controller.go:468]: pls start the error msg with lowercase

File: controllers/keda/scaledobject_controller.go [hunk 3]
```diff
@@ -437,6 +451,31 @@ func (r *ScaledObjectReconciler) ensureHPAForScaledObjectExists(ctx context.Cont
...
+		return false, err
+	}
+
+	if err := r.deleteHPA(ctx, logger, scaledObject, foundHpa); err != nil {
+		logger.Error(err, "Failed to delete HPA from cluster")
```
Comment (zroubalik) [inline controllers/keda/scaledobject_controller.go:473]: pls start the error msg with lowercase

File: controllers/keda/scaledobject_controller.go [hunk 4]
```diff
@@ -197,6 +197,20 @@ func (r *ScaledObjectReconciler) Reconcile(ctx context.Context, req ctrl.Request
...
+	_, paused := scaledObject.GetAnnotations()[kedacontrollerutil.PausedReplicasAnnotation]
+	if paused {
+		logger.Info("ScaledObject is paused, so skipping the request.")
+		if err := r.stopScaleLoop(ctx, logger, scaledObject); err != nil {
+			return "Failed to stop the scale loop for paused ScaledObject", err
+		}
+		if deleted, err := r.ensureHPAForScaledObjectIsDeleted(ctx, logger, scaledObject); !deleted {
+			return "Failed to delete HPA for paused ScaledObject", err
+		}
+		return kedav1alpha1.ScaledObjectConditionReadySuccessMessage, nil
```
Comment (zroubalik) [inline controllers/keda/scaledobject_controller.go:211]: We shouldn't probaly return here Ready Success, but we should probably introduce a new [Condition](https://github.com/kedacore/keda/blob/main/apis/keda/v1alpha1/condition_types.go) on the ScaledObject - `Paused`

**Review by zroubalik — COMMENTED** [review]
Thanks for the contribution, there are some minor nits and we should also introduce a new Condition in the ScaledObject.Status.

File: controllers/keda/scaledobject_controller.go (hunk 1 above)
Comment (tobotg) [reply controllers/keda/scaledobject_controller.go]: sure thing

File: controllers/keda/scaledobject_controller.go (hunk 2 above)
Comment (tobotg) [reply controllers/keda/scaledobject_controller.go]: done

File: controllers/keda/scaledobject_controller.go (hunk 4 above)
Comment (tobotg) [reply controllers/keda/scaledobject_controller.go]: done

File: apis/keda/v1alpha1/condition_types.go [hunk 5]
```diff
@@ -39,6 +39,8 @@ const (
 	ScaledObjectConditionReadySucccesReason = "ScaledObjectReady"
 	// ScaledObjectConditionReadySuccessMessage defines the default Message for correct ScaledObject
 	ScaledObjectConditionReadySuccessMessage = "ScaledObject is defined correctly and is ready for scaling"
+	// ScaledObjectConditionPausedMessage defines the default Message for paused ScaledObject
+	ScaledObjectConditionPausedMessage = "ScaledObject is paused"
```
Comment (zroubalik) [inline apis/keda/v1alpha1/condition_types.go:43]: I was thinking about adding a new Condition, not just message.

Comment (tobotg) [reply apis/keda/v1alpha1/condition_types.go:47]: I now added a new Paused condition. Please have a look

**Review by zroubalik — COMMENTED** [review]
Looking good, could you please add a marker to CRD to show PAUSED column? 
Probably before the AGE column:
https://github.com/kedacore/keda/blob/main/apis/keda/v1alpha1/scaledobject_types.go#L36

**Comment by tobotg** [comment]
> Looking good, could you please add a marker to CRD to show PAUSED column and regenerate the CRD (`make generate`)?
> Probably before the AGE column:
> https://github.com/kedacore/keda/blob/main/apis/keda/v1alpha1/scaledobject_types.go#L36

Sure thing. I added it and run `make manifests`.

**Review by zroubalik — COMMENTED** [review]
the e2e test for paused feature fails :(

**Comment by tobotg** [comment]
> the e2e test for paused feature fails :(

ok thanks @zroubalik , I'll have a look at the pause_scaling_test logs, I guess this is what failed (I can't seem to find the details of the failure in the GitHub actions link)

**Comment by tobotg** [comment]
@zroubalik The e2e tests are passing in my cluster, but I suspect that the test needs more time to recover the scaling loop (loads might be inducing some more delay), so I'm increasing the wait time. Could you please trigger another run when you get a chance? Thanks

**Comment by tobotg** [comment]
@zroubalik 

> /run-e2e pause
> **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/5177647950)

That's weird. I'll need to have a deeper look later, as I'm at loss understanding the failures here.

**Comment by zroubalik** [comment]
> @zroubalik
> 
> > /run-e2e pause
> > **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/5177647950)
> 
> That's weird. I'll need to have a deeper look later, as I'm at loss understanding the failures here.

Seems like the testing deployment is not even initally scaled out, it stays on 0 replicas.

**Comment by tobotg** [comment]
> > @zroubalik
> > > /run-e2e pause
> > > **Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/5177647950)
> > 
> > 
> > That's weird. I'll need to have a deeper look later, as I'm at loss understanding the failures here.
> 
> Seems like the testing deployment is not even initally scaled out, it stays on 0 replicas.

Yes, that's exactly what is puzzling me. Need to sort it out!

**Comment by tobotg** [comment]
I made two changes to the test
- use a much smaller nginx image to speed up deployment
- make the test wait for the monitored deployment to hit its target replica count before proceeding
@zroubalik

**Comment by zroubalik** [comment]
@tobotg I run your branch locally and got the same error as we can see here in the PR.

**Comment by tobotg** [comment]
> @tobotg I ran your branch locally and got the same error as we can see here in the PR.

@zroubalik  Interesting that you're able to reproduce it locally, as I'm not able to reproduce it here. Any chance you can share Keda logs and app:pause-scaling-test and app:pause-scaling-test-monitored logs? That could be helpful for debugging. Thanks in advance.

**Comment by tobotg** [comment]
@zroubalik I had some time tonight to look into this issue, and submitted changes to the PR. Could you please trigger an e2e test when you get a chance? Thanks

**Review by zroubalik — APPROVED** [review]
/lgtm

Thanks @tobotg! Awesome job, it is a great improvement!
