### PR TITLE
Fix waitfordeploymentreplicareadycount duration logs

### LINKED ISSUE #6972: Incorrect log lines in e2e tests
In the tests, a specific time is waited for a `TestScaleIn` or `TestScaleOut`. These times may not match the log entry.
For example, the Dynatrace scaler states that it waits 60 seconds and does so three times, so 3 minutes.
If it fails, a log entry appears stating that it failed to complete the process within the specified timeframe. The example below states 2 minutes. That is incorrect, it should be 3 minutes.

https://github.com/kedacore/keda/blob/56a023d95864d4219f3109ba5a31ca0fe84ee05b/tests/scalers/dynatrace/dynatrace_test.go#L165-L171

This may be incorrect for other scalers.

This issue is here to see where this might be incorrect and correct this.

### PR DESCRIPTION
**Pull request by elieser1101**
Updated test logs to reflect the amount of time the assertion actually takes, only changed the ones using https://github.com/kedacore/keda/blob/main/tests/helper/helper.go#L466

Time for the assertion to fail is `iterations * intervalSeconds`
NOTE: no test changed, only the logging. Because of this Im not sure if most of the checklist bellow make sense for this PR
### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #6972

### CODE REVIEW

**Comment by elieserr** [comment]
cc: @rickbrouwer

File: tests/internals/scaling_modifiers/scaling_modifiers_test.go [hunk 1]
```diff
@@ -282,7 +282,7 @@ func TestScalingModifiers(t *testing.T) {
 
 	// we ensure that the metrics api server is up and ready
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, metricsServerDeploymentName, namespace, 1, 60, 2),
-		"replica count should be 1 after 1 minute")
+		"replica count should be 1 after 2 minute")
```
Comment (rickbrouwer) [inline tests/internals/scaling_modifiers/scaling_modifiers_test.go]:
```suggestion
		"replica count should be 1 after 2 minutes")
```

File: tests/internals/scaling_modifiers/scaling_modifiers_test.go [hunk 2]
```diff
@@ -307,7 +307,7 @@ func testFormula(t *testing.T, kc *kubernetes.Clientset, data templateData) {
 	assert.NoErrorf(t, err, "cannot scale workload deployment - %s", err)
 
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, "depl-workload-base", namespace, 2, 12, 10),
-		"replica count should be %d after 1 minute", 2)
+		"replica count should be %d after 2 minute", 2)
```
Comment (rickbrouwer) [inline tests/internals/scaling_modifiers/scaling_modifiers_test.go]:
```suggestion
		"replica count should be %d after 2 minutes", 2)
```

File: tests/internals/scaling_modifiers/scaling_modifiers_test.go [hunk 3]
```diff
@@ -326,7 +326,7 @@ func testFormula(t *testing.T, kc *kubernetes.Clientset, data templateData) {
 
 	// we ensure that the metrics api server is up and ready
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, metricsServerDeploymentName, namespace, 1, 60, 2),
-		"replica count should be 1 after 1 minute")
+		"replica count should be 1 after 2 minute")
```
Comment (rickbrouwer) [inline tests/internals/scaling_modifiers/scaling_modifiers_test.go]:
```suggestion
		"replica count should be 1 after 2 minutes")
```

File: tests/scalers/gcp/gcp_cloud_tasks_workload_identity/gcp_cloud_tasks_workload_identity_test.go [hunk 4]
```diff
@@ -295,5 +295,5 @@ func testScaleIn(t *testing.T, kc *kubernetes.Clientset) {
 
 	t.Log("--- waiting for replicas to scale in to zero ---")
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, deploymentName, testNamespace, 0, 30, 10),
-		"replica count should be 0 after five minute")
+		"replica count should be 0 after 5 minute")
```
Comment (rickbrouwer) [inline tests/scalers/gcp/gcp_cloud_tasks_workload_identity/gcp_cloud_tasks_workload_identity_test.go]:
```suggestion
		"replica count should be 0 after 5 minutes")
```

File: tests/scalers/gcp/gcp_pubsub/gcp_pubsub_test.go [hunk 5]
```diff
@@ -293,5 +293,5 @@ func testScaleIn(t *testing.T, kc *kubernetes.Clientset) {
 
 	t.Log("--- waiting for replicas to scale in to zero ---")
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, deploymentName, testNamespace, 0, 30, 10),
-		"replica count should be 0 after five minute")
+		"replica count should be 0 after 5 minute")
```
Comment (rickbrouwer) [inline tests/scalers/gcp/gcp_pubsub/gcp_pubsub_test.go]:
```suggestion
		"replica count should be 0 after 5 minutes")
```

File: tests/scalers/kubernetes_workload/kubernetes_workload_test.go [hunk 6]
```diff
@@ -131,24 +131,24 @@ func testScaleOut(t *testing.T, kc *kubernetes.Clientset) {
 	// scale monitored deployment to 5 replicas
 	KubernetesScaleDeployment(t, kc, monitoredDeploymentName, 5, testNamespace)
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, sutDeploymentName, testNamespace, 5, 60, 2),
-		"replica count should be 5 after 1 minute")
+		"replica count should be 5 after 2 minute")
```
Comment (rickbrouwer) [inline tests/scalers/kubernetes_workload/kubernetes_workload_test.go]:
```suggestion
		"replica count should be 5 after 2 minutes")
```

File: tests/scalers/kubernetes_workload/kubernetes_workload_test.go [hunk 7]
```diff
@@ -131,24 +131,24 @@ func testScaleOut(t *testing.T, kc *kubernetes.Clientset) {
...
 
 	// scale monitored deployment to 10 replicas
 	KubernetesScaleDeployment(t, kc, monitoredDeploymentName, 10, testNamespace)
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, sutDeploymentName, testNamespace, 10, 60, 2),
-		"replica count should be 10 after 1 minute")
+		"replica count should be 10 after 2 minute")
```
Comment (rickbrouwer) [inline tests/scalers/kubernetes_workload/kubernetes_workload_test.go]:
```suggestion
		"replica count should be 10 after 2 minutes")
```

File: tests/scalers/kubernetes_workload/kubernetes_workload_test.go [hunk 8]
```diff
@@ -131,24 +131,24 @@ func testScaleOut(t *testing.T, kc *kubernetes.Clientset) {
...
 }
 
 func testScaleIn(t *testing.T, kc *kubernetes.Clientset) {
 	// scale monitored deployment to 5 replicas
 	KubernetesScaleDeployment(t, kc, monitoredDeploymentName, 5, testNamespace)
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, sutDeploymentName, testNamespace, 5, 60, 2),
-		"replica count should be 5 after 1 minute")
+		"replica count should be 5 after 2 minute")
```
Comment (rickbrouwer) [inline tests/scalers/kubernetes_workload/kubernetes_workload_test.go]:
```suggestion
		"replica count should be 5 after 2 minutes")
```

File: tests/scalers/kubernetes_workload/kubernetes_workload_test.go [hunk 9]
```diff
@@ -131,24 +131,24 @@ func testScaleOut(t *testing.T, kc *kubernetes.Clientset) {
...
 
 	// scale monitored deployment to 0 replicas
 	KubernetesScaleDeployment(t, kc, monitoredDeploymentName, 0, testNamespace)
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, sutDeploymentName, testNamespace, 0, 60, 2),
-		"replica count should be 0 after 1 minute")
+		"replica count should be 0 after 2 minute")
```
Comment (rickbrouwer) [inline tests/scalers/kubernetes_workload/kubernetes_workload_test.go]:
```suggestion
		"replica count should be 0 after 2 minutes")
```

File: tests/scalers/redis/redis_standalone_streams_lag/redis_standalone_streams_lag_test.go [hunk 10]
```diff
@@ -208,12 +208,12 @@ func testScaleOut(t *testing.T, kc *kubernetes.Clientset, data templateData, num
 	KubectlReplaceWithTemplate(t, data, "insertJobTemplate", insertJobTemplate)
 
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, deploymentName, testNamespace, maxReplicas, 60, 1),
-		"replica count should be %d after 3 minutes", maxReplicaCount)
+		"replica count should be %d after 1 minutes", maxReplicaCount)
```
Comment (rickbrouwer) [inline tests/scalers/redis/redis_standalone_streams_lag/redis_standalone_streams_lag_test.go]:
```suggestion
		"replica count should be %d after 1 minute", maxReplicaCount)
```

File: tests/scalers/redis/redis_standalone_streams_lag/redis_standalone_streams_lag_test.go [hunk 11]
```diff
@@ -208,12 +208,12 @@ func testScaleOut(t *testing.T, kc *kubernetes.Clientset, data templateData, num
...
 }
 
 func testScaleIn(t *testing.T, kc *kubernetes.Clientset, minReplicas int) {
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, deploymentName, testNamespace, minReplicas, 60, 1),
-		"replica count should be %d after 3 minutes", minReplicaCount)
+		"replica count should be %d after 1 minutes", minReplicaCount)
```
Comment (rickbrouwer) [inline tests/scalers/redis/redis_standalone_streams_lag/redis_standalone_streams_lag_test.go]:
```suggestion
		"replica count should be %d after 1 minute", minReplicaCount)
```

File: tests/secret-providers/trigger_auth_bound_service_account_token/trigger_auth_bound_service_account_token_test.go [hunk 12]
```diff
@@ -344,7 +344,7 @@ func testScaleOut(t *testing.T, kc *kubernetes.Clientset, data templateData) {
 	KubectlReplaceWithTemplate(t, data, "updateMetricTemplate", updateMetricTemplate)
 
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, deploymentName, testNamespace, maxReplicaCount, 60, maxReplicaCount),
-		"replica count should be %d after 3 minutes", maxReplicaCount)
+		"replica count should be %d after 1 minutes", maxReplicaCount)
```
Comment (rickbrouwer) [inline tests/secret-providers/trigger_auth_bound_service_account_token/trigger_auth_bound_service_account_token_test.go]:
```suggestion
		"replica count should be %d after 1 minute", maxReplicaCount)
```

**Review by rickbrouwer — CHANGES_REQUESTED** [review]
Great! Thank you!
A few minor nits

**Review by zroubalik — APPROVED** [review]
Thanks!

Once the comments from @rickbrouwer are resolved, we can merge

File: tests/scalers/cron/cron_test.go [hunk 13]
```diff
@@ -126,11 +126,11 @@ func getTemplateData() (templateData, []Template) {
 func testScaleOut(t *testing.T, kc *kubernetes.Clientset) {
 	t.Log("--- testing scale out ---")
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, deploymentName, testNamespace, 4, 60, 2),
-		"replica count should be 4 after 1 minute")
+		"replica count should be 4 after 2 minute")
```
Comment (rickbrouwer) [inline tests/scalers/cron/cron_test.go]:
```suggestion
		"replica count should be 4 after 2 minutes")
```

File: tests/scalers/cron/cron_test.go [hunk 14]
```diff
@@ -126,11 +126,11 @@ func getTemplateData() (templateData, []Template) {
...
 }
 
 func testScaleIn(t *testing.T, kc *kubernetes.Clientset) {
 	t.Log("--- testing scale in ---")
 	assert.True(t, WaitForDeploymentReplicaReadyCount(t, kc, deploymentName, testNamespace, 1, 60, 2),
-		"replica count should be 1 after 1 minute")
+		"replica count should be 1 after 2 minute")
```
Comment (rickbrouwer) [inline tests/scalers/cron/cron_test.go]:
```suggestion
		"replica count should be 1 after 2 minutes")
```

**Review by rickbrouwer — APPROVED** [review]
❤️

**Comment by elieserr** [comment]
All check have passed but I see merging is blocked because need 2 approvers with write access. Not sure who can help @rickbrouwer @zroubalik 
Thanks for the reviews and help!

**Comment by elieserr** [comment]
friendly reminder, any reason for this to not get merged?

**Comment by rickbrouwer** [comment]
> friendly reminder, any reason for this to not get merged?

Appreciate your patience! Just waiting for the final merge, should be done soon.
