### PR TITLE
fix: apply fallback in polling loop to enable scaling from zero

### LINKED ISSUE #7239: KEDA fallback does not scale from 0 to 1 when metrics cannot be fetched and minReplicaCount is 0
### Report

When using KEDA with the following ScaledObject configuration (Helm template below), fallback is triggered if metrics cannot be fetched. However, if minReplicaCount is set to 0, the deployment does not scale from 0 to 1 as expected when fallback is active.

```
fallback:
    failureThreshold: 1
    replicas: 1 
    behavior: currentReplicasIfHigher
minReplicaCount: 0
maxReplicaCount: 6
  triggers:
    - type: prometheus
      metricType: AverageValue
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc:9090
        metricName: redis_sidekiq_queue_backlog_total
        query: sum(redis_key_size{key=~"{{ $scaler.queueList }}",namespace="....",service="..."})
        threshold: "{{ $scaler.queueBacklog }}"
```

### Expected Behavior

When fallback is triggered and replicas: 1 is set, deployment should scale from 0 to 1.

### Actual Behavior

- Fallback is triggered (confirmed in events/logs).
- Replica count remains at 0, does not scale up to 1.

### Steps to Reproduce the Problem

1. Deploy ScaledObject with minReplicaCount: 0 and fallback as above.
2. Cause metric source to fail (scale down prometheus).
3. Observe fallback is triggered but no scaling from 0 to 1.

### Logs from KEDA operator

```
ERROR 2025-11-07T15:05:01.443182024Z 2025-11-07T15:05:01Z DEBUG scale_handler Getting metrics and activity from scaler {"scaledObject.Namespace": "....", "scaledObject.Name": "....", "scaler": "prometheusScaler", "metricName": "s0-prometheus", "metrics": [], "activity": false, "scalerError": "Get \"http://prometheus-operated.monitoring.svc:9090/api/v1/query?query=sum%28tasks_held%7Bprotocol%3D%22s3%22%7D%29&time=2025-11-07T15:05:01Z\": dial tcp: lookup prometheus-operated.monitoring.svc on 10.56.0.10:53: no such host"}
ERROR 2025-11-07T15:05:01.443185323Z 2025-11-07T15:05:01Z ERROR scale_handler error getting scale decision {"scaledObject.Namespace": "...", "scaledObject.Name": "....", "scaler": "prometheusScaler", "error": "Get \"http://prometheus-operated.monitoring.svc:9090/api/v1/query?query=sum%28tasks_held%7Bprotocol%3D%22s3%22%7D%29&time=2025-11-07T15:05:01Z\": dial tcp: lookup prometheus-operated.monitoring.svc on 10.56.0.10:53: no such host"}
ERROR 2025-11-07T15:05:01.443188010Z github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
ERROR 2025-11-07T15:05:01.443214917Z /workspace/pkg/scaling/scale_handler.go:815
ERROR 2025-11-07T15:05:01.443217848Z github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState.func1
ERROR 2025-11-07T15:05:01.443220922Z /workspace/pkg/scaling/scale_handler.go:662
ERROR 2025-11-07T15:05:01.443236562Z 2025-11-07T15:05:01Z DEBUG scale_handler Removing entry from ScalersCache {"key": "scaledobject....."}
ERROR 2025-11-07T15:05:01.443242155Z 2025-11-07T15:05:01Z DEBUG scale_handler scaler error encountered, clearing scaler cache {"scaledObject.Namespace": "....", "scaledObject.Name": "...."}
ERROR 2025-11-07T15:05:01.443247830Z 2025-11-07T15:05:01Z DEBUG events Get "http://prometheus-operated.monitoring.svc:9090/api/v1/query?query=sum%28tasks_held%7Bprotocol%3D%22s3%22%7D%29&time=2025-11-07T15:05:01Z": dial tcp: lookup prometheus-operated.monitoring.svc on 10.45.0.20:53: no such host {"type": "Warning", "object": {"kind":"ScaledObject","namespace":"...","name":"....","uid":"....","apiVersion":"keda.sh/v1alpha1","resourceVersion":"1762464509434479012"}, "reason": "KEDAScalerFailed"}
ERROR 2025-11-07T15:05:01.443252113Z 2025-11-07T15:05:01Z DEBUG scaleexecutor ScaleTarget will fallback to Fallback.Replicas after Fallback.FailureThreshold {"scaledobject.Name": ".....", "scaledObject.Namespace": "....", "scaleTarget.Name": "...."}
ERROR 2025-11-07T15:05:01.543416968Z github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).GetMetricsAndActivity

```

### KEDA Version

2.18.1

### Kubernetes Version

1.33

### Platform

Google Cloud

### Scaler Details

_No response_

### Anything else?

We are currently unable to set minReplicaCount to 0 in our KEDA ScaledObject configuration. If we do set it to 0 and Prometheus goes down, our deployment can potentially remain at 0 replicas until Prometheus is available again—even if fallback is triggered. This means our application may not recover automatically when metrics cannot be fetched.

Thank you for your help and consideration!

### PR DESCRIPTION
**Pull request by rickbrouwer**
When a ScaledObject is scaled to zero and the scaler encounters an error, the fallback mechanism is only triggered during HPA metric requests via `GetScaledObjectMetrics`, but not during the polling loop in `getScaledObjectState`. This caused the ScaledObject to remain at zero replicas indefinitely when errors occurred, as the polling loop would continuously fail without activating the fallback, preventing HPA from ever being consulted.

Fallback now works in both, HPA requests and polling interval checks.

The only question I have is whether it's by design that it doesn't switch to Fallback with 0 replicas, but I can't think of that myself. Please consider this when considering whether this was a deliberate choice. If not, I believe this PR resolves the issue.

Some extra new info;

It turned out to be a more change than I anticipated. I initially thought I'd add a simple fallback to `getScalerState`, but it turned out that scalingModifiers started having issues.
Therefore, I had to make some further adjustments to ensure the fallback worked properly from all positions.

### Checklist

- [X] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [X] Tests have been added
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #7239

### CODE REVIEW

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19261381657)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19298231840)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19299138690)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19300104866)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19300115988)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19304500376)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19306608629)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19462292648)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19497507640)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19510749755)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19608980758)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19895603186)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19896077556)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19898566377)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19901935524)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19921829425)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19964147172)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/19985449047)

**Comment by JorTurFer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/20009504923)

**Review by JorTurFer — APPROVED** [review]

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/20027160003)

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/20058292046)

File: pkg/scaling/scale_handler.go [hunk 1]
```diff
@@ -441,6 +441,57 @@ func (h *scaleHandler) ClearScalersCache(ctx context.Context, scalableObject int
 /// ----------             ScaledObject related methods               --------- ///
 /// --------------------------------------------------------------------------- ///
 
+// processMetricsWithFallback processes metrics with fallback support and handles metric recording
+func (h *scaleHandler) processMetricsWithFallback(
```
Comment (zroubalik) [inline pkg/scaling/scale_handler.go]: I'd personally prefer if we don't use this style (each param on a new line), I know that it has some benefits, but for the code clarity we should try to make the style consistent in the code base.

So if you are not tottaly against, could you please fix this across this PR?

Comment (rickbrouwer) [reply pkg/scaling/scale_handler.go]: sure! no problem.

**Comment by rickbrouwer** [comment]
/run-e2e internals
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/20132011505)

File: pkg/scaling/scale_handler.go [hunk 2]
```diff
@@ -441,6 +441,46 @@ func (h *scaleHandler) ClearScalersCache(ctx context.Context, scalableObject int
 /// ----------             ScaledObject related methods               --------- ///
 /// --------------------------------------------------------------------------- ///
 
+// processMetricsWithFallback processes metrics with fallback support and handles metric recording
+func (h *scaleHandler) processMetricsWithFallback(ctx context.Context, rawMetrics []external_metrics.ExternalMetricValue, rawErr error, metricName string, triggerName string, triggerIndex int, scaledObject *kedav1alpha1.ScaledObject, metricSpec v2.MetricSpec, sendRawMetricsCondition bool, logger logr.Logger) ([]external_metrics.ExternalMetricValue, bool, error) {
+	// check if we need to set a fallback
+	metrics, fallbackActive, err := fallback.GetMetricsWithFallback(
```
Comment (zroubalik) [inline pkg/scaling/scale_handler.go]: @rickbrouwer sorry for bothering you, could you please also fix it here and below where `h.processMetricsWithFallback(` is called?

Comment (rickbrouwer) [reply pkg/scaling/scale_handler.go]: no problem, I think I've adjusted everything now

**Comment by rickbrouwer** [comment]
/run-e2e fallback
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/20133636573)
