### PR TITLE
Return 1 or 0 instead of -1 when detecting an invalid offset in Kafka

### LINKED ISSUE #2612: Kafka scaler reports -2 and scale to maxReplicas
### Report

We have a situation where Kafka scaler reports -2 and the HPA scale to the maxReplicas.
A CPU scaler is also defined but it reports 1% usage so the desired replicas count should be 1 not 3.

The following information comes from a kubectl describe on the HPA
```
Name:                                                                        keda-hpa-vcstream-out-listener-kafka-geco
Namespace:                                                                   vcstream-dev
Labels:                                                                      app.kubernetes.io/managed-by=Helm
                                                                             app.kubernetes.io/name=keda-hpa-vcstream-out-listener-kafka-geco
                                                                             app.kubernetes.io/part-of=vcstream-out-listener-kafka-geco
                                                                             app.kubernetes.io/version=2.5.0
                                                                             scaledobject.keda.sh/name=vcstream-out-listener-kafka-geco
Annotations:                                                                 <none>
CreationTimestamp:                                                           Tue, 08 Feb 2022 17:09:07 +0100
Reference:                                                                   Deployment/vcstream-out-listener-kafka-geco
Metrics:                                                                     ( current / target )
  "s1-kafka-private_dkt_out_listener_kafka_geco_v1" (target average value):  -2 / 500
  resource cpu on pods  (as a percentage of request):                        1% (3m) / 75%
Min replicas:                                                                1
Max replicas:                                                                3
Deployment pods:                                                             3 current / 3 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange   the desired count is within the acceptable range
```

Other scalers defined the same way and connected to the same Kafka broker works as expected.

### Expected Behavior

As there is no lag and no CPU, HPA need to scale to the minReplicas wich is 1.

### Actual Behavior

HPA scale to maxReplicas wich is 3.

### Steps to Reproduce the Problem

Here is the sclaled objet definition we use:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vcstream-out-listener-kafka-geco
spec:
  scaleTargetRef:
    name: vcstream-out-listener-kafka-geco
  minReplicaCount: 1
  maxReplicaCount:  3
  cooldownPeriod: 60
  fallback:
    failureThreshold: 3
    replicas: 1
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "75"
  - type: kafka      
    metadata:
      bootstrapServers: "redacted"
      consumerGroup: vcstream-out-listener-kafka-geco
      topic:  private_dkt_out_listener_kafka_geco_v1
      lagThreshold: "500"
      offsetResetPolicy: latest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
```

### Logs from KEDA operator

```
example
```

### KEDA Version

_No response_

### Kubernetes Version

_No response_

### Platform

Google Cloud

### Scaler Details

cpu, kafka

### Anything else?

Maybe the issue is that the lag is not reported and Keda returns -2 instead of 0 when there is no lag ?

### PR DESCRIPTION
**Pull request by RamCohen**
When getting the consumer offset of a Kafka topic for which no offset
was committed yet, the scaler returns with -1 instead of 0, which
causes to scale to the maximum number of replicas.

This fix changes the behavior to return in that case either '1' (the default) or '0', depending on a new scaler parameter scaleToZeroOnInvalidOffset which default to 'false'

Also fixed some typos and used interim variables for error strings.

Fixes #2612 #2033

### CODE REVIEW

**Comment by JorTurFer** [comment]
> /run-e2e kafka*

Hi @RamCohen , only people with write permission can trigger this.
Now we have 2 execution in progress but I'll trigger this after those finish

**Comment by JorTurFer** [comment]
Does this make sense @kedacore/keda-core-contributors ?

**Review by zroubalik — COMMENTED** [review]
Looking good, thanks! Could you please open documentation PR?

**Comment by zroubalik** [comment]
@bpinske @PaulLiang1 PTAL

**Comment by PaulLiang1** [comment]
> @bpinske @PaulLiang1 PTAL

looks good. 
also replied on https://github.com/kedacore/keda/issues/2612#issuecomment-1054866086

**Comment by zroubalik** [comment]
I wonder whether we can extend [the e2e test ](https://github.com/kedacore/keda/blob/main/tests/scalers/kafka.test.ts) to cover this scenario? I think that creating a topic without any message should cause the invalid offset problem, right?

**Comment by zroubalik** [comment]
> I wonder whether we can extend [the e2e test ](https://github.com/kedacore/keda/blob/main/tests/scalers/kafka.test.ts) to cover this scenario? I think that creating a topic without any message should cause the invalid offset problem, right?

@RamCohen do you think you can contribute this?

**Comment by RamCohen** [comment]
I'll have a look, but I'm not sure where have we landed with the proposed solution vis-a-vis having a configuration parameter for returning either 0 or 1 and what would be its default

**Comment by JorTurFer** [comment]
> thanks for this pull request! we are having problems in production due to this issue :) do we have an estimate when the new version will be released?

hi @rrmcclymont ,
Our plan is to release v2.7 on May, hopefully on May 9th. I guess that this PR will be merged before that date so it should be included on v2.7

**Comment by rrmcclymont** [comment]
thanks @JorTurFer  glad to see that we will include this fix in the following release :)

**Comment by RamCohen** [comment]
Added tests

File: pkg/scalers/kafka_scaler.go [hunk 1]
```diff
@@ -336,17 +357,25 @@ func (s *kafkaScaler) getConsumerOffsets(topicPartitions map[string][]int32) (*s
...
-		kafkaLog.V(0).Info(fmt.Sprintf("invalid offset found for topic %s in group %s and partition %d, probably no offset is committed yet", topic, s.metadata.group, partitionID))
-		return invalidOffset, fmt.Errorf("invalid offset found for topic %s in group %s and partition %d, probably no offset is committed yet", topic, s.metadata.group, partitionID)
+		retVal := int64(1)
+		if s.metadata.scaleToZeroOnInvalidOffset {
+			retVal = 0
+		}
+		errMsg := fmt.Errorf(
+			"invalid offset found for topic %s in group %s and partition %d, probably no offset is committed yet. Returning with lag of %d",
+			topic, s.metadata.group, partitionID, retVal)
+		kafkaLog.V(0).Info(errMsg.Error())
```
Comment (zroubalik) [inline pkg/scalers/kafka_scaler.go:373]: I wonder whether we want to return error?

Comment (rrmcclymont) [reply pkg/scalers/kafka_scaler.go:373]: @zroubalik I have some topics that are inactive for some time and the offset is deleted (after a week ) therefore, when we receive another event to that topic keda doesn't work because it return -1 instead of 1. In my opinion, it should return 0 instead -1 (don't fail) because the offsets were deleted in the topic so it's ok to trace that if you want but it should return error, right?

Comment (zroubalik) [reply pkg/scalers/kafka_scaler.go:373]: I might be wrong, but if you set the new property that's introduced in this PR, it should return 0 and for this case I am asking if we should print error. I might be missing something of course.

Comment (RamCohen) [reply pkg/scalers/kafka_scaler.go]: I agree. Changed to not return error. This btw does not change the logic of the two places using this method as they either ignore the error or check that also the returning lag is -1

Comment (zroubalik) [reply pkg/scalers/kafka_scaler.go]: Agree. Yeah, that's what I noticed as well.

**Comment by zroubalik** [comment]
@RamCohen could please open docs PR for this?

**Comment by RamCohen** [comment]
> 

Could you give me an example of what you mean ?

**Review by zroubalik — APPROVED** [review]
LGTM,

@RamCohen so the last bit is Changelog

**Comment by akshay201** [comment]
What is the expected behaviour now.
    If we do not have any consumer group created for a topic and new messages have arrived in topic, in this case I suppose invalid offset will be returned and keda will return 0 or scale to 0 if `scaleToZeroOnInvalidOffset` is set to true. Doubt is then if there are no consumers present, there would be no consumer group and offset will be invalid always. How is the problem related to this is solved with this so that consumers are scaled up on invalid offset but messages present in topic?

We want to scale consumers to 0 when there are no messages in topic and scale back consumers if there any new messages.

Apologies if I did not understand or if I am missing something here. Thanks.

**Comment by akshay201** [comment]
@pnorth1 It seems like issue is resolved from the documentation of latest version
https://keda.sh/docs/2.0/scalers/apache-kafka/#new-consumers-and-offset-reset-policy

Did you try new version? 

If anyone else tried the same I would like to hear if it worked.
