### PR TITLE
fix: avoid int64 overflow in milli-quantity conversion for large metric values

### LINKED ISSUE #7441: Averaged Value for Keda Metrics-API is Zero even though It's Large Value
### Report

The issue here  is the current value is reported as zero according to keda scaledobject's hpa based on trigger scaler of type metrics-api. The correct value should be in range of quintillion. 

### Expected Behavior

The expected behavior is to report the exact quintillion value for number. 

### Actual Behavior

The actual behavior is consistently being reported for external metric as zero. 

### Steps to Reproduce the Problem

1. Define metrics-api trigger that is based on metric whose true value is large (in range of quintillion). 
2. Describe the hpa and see the current value remains zero over time.

### Logs from KEDA operator

Keda operator logs is not the issue here so it won't be that relevant... 

### KEDA Version

2.17.0

### Kubernetes Version

1.32

### Platform

Microsoft Azure

### Scaler Details

Metrics-API

### Would you be open to contributing a fix?

Maybe

### Anything else?

Here is the screenshot of the true metric value reported on Grafana:

Image

### PR DESCRIPTION
**Pull request by MunemHashmi**
Fix int64 overflow in `GetMetricTargetMili()` and `GenerateMetricInMili()` that caused very large metric values (>~9.2×10¹⁵) to be reported as zero.

### Root Cause

Both functions computed `int64(value * 1000)` to create milli-quantities. When `value * 1000` exceeds `math.MaxInt64` (~9.22×10¹⁸), the conversion silently overflows, producing a negative number that gets reported as zero by the HPA.

### Fix

Extract a shared `quantityFromFloat64()` helper that:
1. Guards against NaN and Inf inputs (treats them as zero to prevent `resource.MustParse` panics)
2. Uses `resource.MustParse(fmt.Sprintf("%.3f", value))` instead of `int64(value * 1000)` + `resource.NewMilliQuantity()`, leveraging `resource.Quantity`'s arbitrary precision to avoid int64 overflow

### Checklist

- [X] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [X] Tests have been added
- [X] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog), only when the change impacts end users
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #7441

### CODE REVIEW

**Comment by rickbrouwer** [comment]
What will happen with this new code when we get a NaN or Inf as result like https://github.com/kedacore/keda/issues/7475?

**Comment by MunemHashmi** [comment]
Good catch @rickbrouwer! The previous code would have had undefined behavior for NaN/Inf (silent int64 cast), but with `resource.MustParse` it would panic on those inputs.

I've pushed a follow-up commit that extracts a `quantityFromFloat64` helper which guards against NaN and Inf by treating them as zero. This prevents operator crashes from malformed metric API responses. Added test coverage for both cases as well.

**Comment by rickbrouwer** [comment]
/run-e2e
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/22948371997)

**Comment by rickbrouwer** [comment]
/run-e2e
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/22955758268)

**Comment by rickbrouwer** [comment]
/run-e2e github_runner*
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/22970716285)

File: pkg/scalers/scaler_test.go [hunk 1]
```diff
@@ -88,6 +89,104 @@ func TestGetMetricTarget(t *testing.T) {
 	}
 }
 
+func TestGetMetricTargetMili(t *testing.T) {
+	cases := []struct {
+		name        string
+		metricType  v2.MetricTargetType
```
Comment (JorTurFer) [inline pkg/scalers/scaler_test.go]: naive question, is the metric type relevant for the conversion? I think that we could make the test more simple just removing it and using the same always if it's not relevant for the parsing

Comment (MunemHashmi) [reply pkg/scalers/scaler_test.go]: You're right, the metric type only affects which struct field gets the quantity, not the conversion itself. Simplified the test to use a single metric type throughout. Thanks\!

**Comment by rickbrouwer** [comment]
/run-e2e internal
**Update:** You can check the progress [here](https://github.com/kedacore/keda/actions/runs/22990904579)
