### PR TITLE
resolve k8s Minor version correctly

### LINKED ISSUE #1176: Up-down scaling behavior configuration is ignored in Kubernetes version >= 18.0
Scaling up-down behavior configuration https://github.com/kedacore/keda/pull/805 is ignored in Kubernetes 19.0 and 18.8 (only 2 versions I checked on). 
Here is info from logs 
```
2020-09-21T07:17:45.828Z        INFO    controllers.ScaledObject        Creating a new HPA      {"ScaledObject.Namespace": "default", "ScaledObject.Name": "kafka-receiver-scaledobject", "HPA.Namespace": "default", "HPA.Name": "keda-hpa-kafka-receiver-scaledobject"}
2020-09-21T07:17:45.968Z        INFO    controllers.ScaledObject        Warning: Ignoring scaledObject.spec.behavior, it is only supported on kubernetes version >= 1.18 {"ScaledObject.Namespace": "default", "ScaledObject.Name": "kafka-receiver-scaledobject", "kubernetes.version": "1.19"}
2020-09-21T07:17:45.968Z        INFO    controllers.ScaledObject        Initializing Scaling logic according to ScaledObject Specification      {"ScaledObject.Namespace": "default", "ScaledObject.Name": "kafka-receiver-scaledobject"}
```

## Expected Behavior
Scaling behavior should be functioning

## Actual Behavior
It's not. Logs confirm that.

## Steps to Reproduce the Problem

  1. Install keda, create ScaledObject with scaledDown, scaleUp advanced config.
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-receiver-scaledobject
spec:
  scaleTargetRef:
    name: test
  pollingInterval: 5
  cooldownPeriod:  5
  minReplicaCount: 1
  maxReplicaCount: 4
  advanced:                                          # Optional. Section to specify advanced options
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 1000
          policies:
          - type: Percent
            value: 1
            periodSeconds: 1000
          - type: Pods
            value: 1
            periodSeconds: 1000
          selectPolicy: Disabled
        scaleUp:
          stabilizationWindowSeconds: 1000
          policies:
          - type: Pods
            value: 1
            periodSeconds: 1000    
          policies:
          - type: Percent
            value: 1
            periodSeconds: 1000   
          selectPolicy: Disabled
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.default:9090
      metricName: sender-metric-test
      threshold: '10'
      query: sum(irate(spring_integration_send_seconds_count{application_name="kafka-receiver"}[1m])) * 10
```
  2. Test it, see that it's not functioning, see logs.

## Specifications

  - **KEDA Version:** *2.0.0 beta*
  - **Platform & Version:** *tested in Minikube*
  - **Kubernetes Version:** *19.0*
  - **Scaler(s):** *Prometheus*

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

k8s version wasn't correctly resolved if `len(Minor) <= 2` 
For example: `18+` vs `19` or `18`

Adding tests

Fixes #1176

### CODE REVIEW

File: pkg/util/k8sversion_test.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+)
+
+type testMetadata struct {
+	comment        string
+	expectedMinor  int
+	expectedPretty string
+	version        *version.Info
+}
+
+var testMetadatas = []testMetadata{
```
Comment (TsuyoshiUshio) [inline pkg/util/k8sversion_test.go:16]: I just curious, how do you choose the test cases. When I see the release, the logic should work. 
https://github.com/kubernetes/kubernetes/releases
However, You assume `1.18+` or `1.19.84324.2`. Where do you find the cases?

**Review by TsuyoshiUshio — APPROVED** [review]
Looks good to me. Well written test cases, and code is simple enough. 
I already approve it, so we can merge it, however, I just want to know how to choose the test case for my learning.

File: pkg/util/k8sversion_test.go (hunk 1 above)
Comment (zroubalik) [reply pkg/util/k8sversion_test.go:16]: @TsuyoshiUshio similar version string is returned by from the cluster in the `version.Info{}` struct.
For example:
- as reported in #1176, minikube returns string `1.19`
- OpenShift cluster I am using returns string `1.18+`
etc

We only care about the minor version (and specifically if it is > 17), so I added a couple of scenarios to check we can always parse the minor version.

Comment (TsuyoshiUshio) [reply pkg/util/k8sversion_test.go:16]: Thank you for sharing!
