### PR TITLE
[BUG-5656] Annotate Jobs with parent ScaledJob generation

### LINKED ISSUE #5656: Restart of keda-operator causes ScaledJob object to be updated
### Report

Restart/Recreation of keda-operator causes ScaledJob object to be updated, which leads to Jobs being rolled out as per the RolloutStrategy.

### Expected Behavior

Restart/Recreation of the keda-operator should not update the ScaledJob object

### Actual Behavior

Restart/Recreation of the keda-operator somehow update the ScaledJob object leading to Jobs being rolled out as per the RolloutStrategy.

### Steps to Reproduce the Problem

1. Kill the keda-operator (with replicas >1).
2. Wait for the keda-operator to be recreated.
3. In the Kubernetes events for the ScaledJob object, around the time the keda-operator was restarted the following events can be seen: 
  i. KEDAJobsCreated
  ii. KEDAScalersStarted

### KEDA Version

2.13.1

### Kubernetes Version

1.27

### Platform

Microsoft Azure

### Scaler Details

_No response_

### Anything else?

This could also be the expected behavior of the keda-operator. However I do not understand why any changes the to keda-operator should affect the ScaledJob object.

### PR DESCRIPTION
**Pull request by josefkarasek**
As reported in #5656, keda-operator Pod restart causes the deletion of existing Jobs (child resources of ScaledJob). The Jobs are re-created immediately, but the state/progress of the running Jobs is lost. 

My approach to fixing this is to maintain relation between the ScaledJob and child Jobs using an Annotation:
`"scaledjob.keda.sh/generation": $(ScaledJob.Generation)`
This way the operator, during startup, will only delete Jobs with `"scaledjob.keda.sh/generation"` that doesn't match the generation of the parent ScaledJob.

### Checklist

- [x] When introducing a new scaler, I agree with the [scaling governance policy](https://github.com/kedacore/governance/blob/main/SCALERS.md)
- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Tests have been added
- [x] Changelog has been updated and is aligned with our [changelog requirements](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#Changelog)
- [x] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [x] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #5656

### CODE REVIEW

File: pkg/scaling/executor/scale_jobs.go [hunk 1]
```diff
@@ -101,6 +101,10 @@ func (e *scaleExecutor) getScalingDecision(scaledJob *kedav1alpha1.ScaledJob, ru
 }
 
 func (e *scaleExecutor) createJobs(ctx context.Context, logger logr.Logger, scaledJob *kedav1alpha1.ScaledJob, scaleTo int64, maxScale int64) {
+	if maxScale <= 0 {
+		logger.Info("No need to create jobs", "Effective maxScale", maxScale)
```
Comment (zroubalik) [inline pkg/scaling/executor/scale_jobs.go:105]: Can we extend this message a bit? the `Effective maxScale` part, it might not be clear to everyone

**Review by zroubalik — COMMENTED** [review]
Looking good, thanks! Could you please also update changelog?

**Review by zroubalik — APPROVED** [review]
LGTM

**Review by zroubalik — COMMENTED** [review]
@josefkarasek the static check si failing on the Changelog entry, it needs to be alphabetically sorted, also please move this into Improvements section - it is an user-facing issue.

The rest looks good, thanks

**Review by zroubalik — APPROVED** [review]
