### PR TITLE
Fix: READY and ACTIVE fields of ScaledJob to show status.

### LINKED ISSUE #1849: READY AND ACTIVE fields of ScaledJob are empty when we run "kubectl get sj"
### Report

When worked with ScaledJob i have noticed that it doesn't show the  `**READY**`  and   `**ACTIVE**`   status when we run `kubectl get sj` In both before and after the scaling. It always blank.

Before scaling
```
$ kubectl get sj
NAME          MAX   TRIGGERS   AUTHENTICATION    READY   ACTIVE   AGE
mongodb-job   100   mongodb    mongodb-trigger                    7s
```
After scaling
```
$ kubectl get sj
NAME          MAX   TRIGGERS   AUTHENTICATION    READY   ACTIVE   AGE
mongodb-job   100   mongodb    mongodb-trigger                    112s
```
Here is the Secrets, TriggerAuthentication and ScaledJob yamls which i have used to test it:

Secrets:
```
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  connect: bW9uZ29kYjovL3Rlc3RfdXNlcjp0ZXN0X3Bhc3N3b3JkQG1vbmdvZGItc3ZjLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvdGVzdA==
```
TriggerAuthentication:
```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: mongodb-trigger
spec:
  secretTargetRef:
  - parameter: connectionString
    name: mongodb-secret
    key: connect

```
ScaledJob:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: mongodb-job
spec:
  jobTargetRef:
    template:
      spec:
       containers:
       - name: pi
         image: perl
         command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
  pollingInterval: 20
  maxReplicaCount: 100
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 10
  triggers:
    - type: mongodb
      metadata:
        dbName: test
        collection: test_collection
        query: '{"region":"eu-1","state":"running","plan":"planA"}'
        queryValue: "1"
        metricName: "global-metric"
      authenticationRef:
        name: mongodb-trigger
```

### Expected Behavior

When we run `kubectl get sj` then it should show   `**READY**`  and   `**ACTIVE**`  status in both before and after scaling.
There status value would be: True, False, Unknown  depending upon the scaling just like we have in  ScaledObject.

### Actual Behavior

When we run `kubectl get sj` then it doesn't show   `**READY**`  and   `**ACTIVE**` status in both before and after scaling.

### Steps to Reproduce the Problem

1. Set-up minikube v1.18.1
2. Deploy mongodb.
3. Create secrets and TA with above yaml and apply it.
4. Create ScaledJob with above yaml's and apply it.
5. Check READY and ACTIVE Status before and after scaling by running kubectl get sj 

### Logs from KEDA operator

No error

### KEDA Version

2.3.0

### Kubernetes Version

1.20

### Platform

Other

### Scaler Details

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Shubham82**
Signed-off-by: Shubham Kuchhal <shubham.kuchhal@india.nec.com>

Fix the READY AND ACTIVE fields of ScaledJob to show Status before and after scaling when we run `kubectl get sj`. and also replace ScaledObject to ScaledJob in comments and error message for ScaledJob.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Changelog has been updated

Fixes #1849

### CODE REVIEW

File: controllers/scaledjob_controller.go [hunk 1]
```diff
@@ -80,47 +81,63 @@ func (r *ScaledJobReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
...
-	err = fmt.Errorf(errMsg)
-	reqLogger.Error(err, "scaledJob.Spec.JobTargetRef not found")
+	if err := kedacontrollerutil.SetStatusConditions(r.Client, reqLogger, scaledJob, &conditions); err != nil {
+		return ctrl.Result{}, err
+	}
 	return ctrl.Result{}, err
 }
 
-// reconcileJobType implemets reconciler logic for K8s Jobs based ScaleObject
+// reconcileJobType implemets reconciler logic for K8s Jobs based ScaledJob
```
Comment (zroubalik) [inline controllers/scaledjob_controller.go:121]:
```suggestion
// reconcileScaledJob implemets reconciler logic for K8s Jobs based ScaledJob
```

**Review by zroubalik — COMMENTED** [review]
Looking good, minor nit and could you please add this to the changelog? Improvements section?

File: controllers/scaledjob_controller.go (hunk 1 above)
Comment (Shubham82) [reply controllers/scaledjob_controller.go:121]: Thanks, @zroubalik for taking a look at this.
I will do update this also.
one more thing Should I also update  Changelog?

Comment (Shubham82) [reply controllers/scaledjob_controller.go]: Hi  @zroubalik 
Addressed the comment, PTAL

Comment (Shubham82) [reply controllers/scaledjob_controller.go]: > Looking good, minor nit and could you please add this to the changelog? (Improvements section)
Sorry I missed your comment

I updated the changelog. PTAL

File: CHANGELOG.md [hunk 2]
```diff
@@ -54,6 +54,7 @@
 - Fix cleanup of removed triggers ([#1768](https://github.com/kedacore/keda/pull/1768))
 - Eventhub Scaler: Add trigger parameter `checkpointStrategy` to support more language-specific checkpoints ([#1621](https://github.com/kedacore/keda/pull/1621))
 - Fix Azure Blob scaler when using multiple triggers with the same `blobContainerName` and added a optional `metricName` field ([#1816](https://github.com/kedacore/keda/pull/1816))
+- Fix READY and ACTIVE fields of ScaledJob to show status when we run `kubectl get sj` ([#1855](https://github.com/kedacore/keda/pull/1855))
```
Comment (zroubalik) [inline CHANGELOG.md:57]: This should be in the ## Unreleased section, KEDA 2.3.0 is already out :)

**Review by zroubalik — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 2 above)
Comment (Shubham82) [reply CHANGELOG.md:57]: oh, by mistake I wrote here, I am changing it now.
 sorry for inconvience.

Comment (Shubham82) [reply CHANGELOG.md]: Addressed the comment. PTAL

**Review by zroubalik — APPROVED** [review]
LGTM, thanks @Shubham82
