### PR TITLE
fix: JetSteam scaler detects leader changes correctly

### LINKED ISSUE #6042: NATS JetStream doesn't detect a leader change
### Report

Currently, if there is a change in the leader due to any reason (manual step-down, disruptions, rotations, etc...) KEDA doesn't detect the change and still request the info to the same node. When a node isn't the consumer leader, it only exposes the current information about in-flight messages. This means that I can have 10k messages pending, but if the node is only processing 100 (because the consumer doesn't allow more), KEDA will see only those 100 instead of the 10k.

### Expected Behavior

KEDA should switch to the new leader automatically

### Actual Behavior

KEDA is stuck using the old leader

### PR DESCRIPTION
**Pull request by JorTurFer**
_Provide a description of what has been changed_

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))

Fixes #6042

### CODE REVIEW

File: pkg/scalers/nats_jetstream_scaler_test.go [hunk 1]
```diff
@@ -440,22 +440,6 @@ func TestNATSJetStreamGetNATSJetstreamServerURL(t *testing.T) {
...
-	mockJetStreamScaler := natsJetStreamScaler{
-		stream:     nil,
-		metadata:   meta,
-		httpClient: http.DefaultClient,
-		logger:     InitializeLogger(&scalersconfig.ScalerConfig{TriggerMetadata: testNATSJetStreamGoodMetadata, TriggerIndex: 0}, "nats_jetstream_scaler"),
-	}
-
-	mockJetStreamScaler.invalidateNATSJetStreamCachedMonitoringData()
-}
-
```
Comment (JorTurFer) [inline pkg/scalers/nats_jetstream_scaler_test.go:458]: This test isn't testing anything

File: pkg/scalers/nats_jetstream_scaler.go [hunk 2]
```diff
@@ -218,20 +218,6 @@ func (s *natsJetStreamScaler) getNATSJetstreamMonitoringData(ctx context.Context
...
-			jetStreamAccountResp, err = s.getNATSJetstreamMonitoringRequest(ctx, natsJetStreamMonitoringLeaderURL)
-			if err != nil {
-				return err
-			}
-
-			s.setNATSJetStreamMonitoringData(jetStreamAccountResp, natsJetStreamMonitoringLeaderURL)
-			return nil
-		}
-
-		// we haven't found the consumer yet, grab the list of hosts and try each one
```
Comment (JorTurFer) [inline pkg/scalers/nats_jetstream_scaler.go:234]: If we reach this code is because we don't know who is the leader indeed. The current leader doesn't match with the previous leader (checked in the if statement just above)

**Review by zroubalik — APPROVED** [review]
