### PR TITLE
Metrics API scaler to support parsing numbers in quotes as well as quantities.

### LINKED ISSUE #1667: Metrics API scaler does not support Quantities
### Report

The metrics API is unable to process Quantities (even simple numeric ones.) This is because they are serialized to strings. KEDA actually returns Quantities itself so this scaler would no be able to process them either.

### Expected Behavior

I receive an API response like this:

```
{"foo":"123"}
```

I am able to reference it like this

```
  triggers:
  - type: metrics-api
    metadata:
      targetValue: "0"
      url: "https://blah"
      valueLocation: "foo"
```

### Actual Behavior

The error:
valueLocation must point to value of type number got: String

### Steps to Reproduce the Problem

1.Make/use an API that returns quantities
2.Point the metrics API scaler at it
3.Observe error

### Logs from KEDA operator

```
example
```

### KEDA Version

2.1.0

### Kubernetes Version

1.17

### Platform

Any

### Scaler Details

metrics-api

PR will be raised to fix issue in a minute

### PR DESCRIPTION
**Pull request by devjoes**
Quantities can now be parsed from a metrics API response. Lots of metrics APIs return Quantity types which get marshalled to strings (KEDA itself actually has this behaviour).
ExternalMetricValue.Value is already a Quantity so there should be no impact on the wider codebase.

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] Tests have been added
- [N/A] A PR is opened to update our Helm chart ([repo](https://github.com/kedacore/charts)) *(if applicable, ie. when deployment manifests are modified)*
- [N/A] A PR is opened to update the documentation on ([repo](https://github.com/kedacore/keda-docs)) *(if applicable)*
- [x] Changelog has been updated

Fixes #1667

### CODE REVIEW

**Comment by zroubalik** [comment]
@turbaszek would you mind looking at this?

File: pkg/scalers/metrics_api_scaler.go [hunk 1]
```diff
@@ -172,39 +172,45 @@ func parseMetricsAPIMetadata(config *ScalerConfig) (*metricsAPIScalerMetadata, e
 }
 
 // GetValueFromResponse uses provided valueLocation to access the numeric value in provided body
-func GetValueFromResponse(body []byte, valueLocation string) (int64, error) {
+func GetValueFromResponse(body []byte, valueLocation string) (*resource.Quantity, error) {
 	r := gjson.GetBytes(body, valueLocation)
+	if r.Type == gjson.String {
+		q, err := resource.ParseQuantity(r.String())
+		if err == nil {
```
Comment (turbaszek) [inline pkg/scalers/metrics_api_scaler.go:179]: What will be returned if the `err!=nil`?

**Review by turbaszek — COMMENTED** [review]
Look reasonable to me, just one question

**Comment by zroubalik** [comment]
@devjoes could you please open another PR with documentation of this feature? in content/docs/2.2 https://github.com/kedacore/keda-docs

File: pkg/scalers/metrics_api_scaler.go (hunk 1 above)
Comment (JoeSainsburys) [reply pkg/scalers/metrics_api_scaler.go:179]: It would revert to the original behaviour and return "valueLocation must point to value of type number got: string"

**Comment by JoeSainsburys** [comment]
@zroubalik  [docs updated](https://github.com/kedacore/keda-docs/pull/401)

File: pkg/scalers/metrics_api_scaler.go (hunk 1 above)
Comment (JoeSainsburys) [reply pkg/scalers/metrics_api_scaler.go]: I've improved the error handling

**Review by zroubalik — APPROVED** [review]
LGTM, thanks!
